/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const AlertDialogProvider: typeof import('./resources/js/composables/useAlertDialog').AlertDialogProvider
  const EffectScope: typeof import('vue').EffectScope
  const computed: typeof import('vue').computed
  const createApp: typeof import('vue').createApp
  const customRef: typeof import('vue').customRef
  const defineAsyncComponent: typeof import('vue').defineAsyncComponent
  const defineComponent: typeof import('vue').defineComponent
  const effectScope: typeof import('vue').effectScope
  const extractStreamingTreeOperations: typeof import('./resources/js/composables/useAiContentTree').extractStreamingTreeOperations
  const getCurrentInstance: typeof import('vue').getCurrentInstance
  const getCurrentScope: typeof import('vue').getCurrentScope
  const getCurrentWatcher: typeof import('vue').getCurrentWatcher
  const getLocale: typeof import('./resources/js/plugins/i18n').getLocale
  const getPosthog: typeof import('./resources/js/plugins/posthog').getPosthog
  const h: typeof import('vue').h
  const i18n: typeof import('./resources/js/plugins/i18n').i18n
  const initAuth: typeof import('./resources/js/plugins/auth').initAuth
  const inject: typeof import('vue').inject
  const installChart: typeof import('./resources/js/plugins/chart').installChart
  const installEcho: typeof import('./resources/js/plugins/echo').installEcho
  const installI18n: typeof import('./resources/js/plugins/i18n').installI18n
  const installPosthog: typeof import('./resources/js/plugins/posthog').installPosthog
  const installVueQuery: typeof import('./resources/js/plugins/vue-query').installVueQuery
  const isFieldVisible: typeof import('./resources/js/composables/useContentSchemaState').isFieldVisible
  const isProxy: typeof import('vue').isProxy
  const isReactive: typeof import('vue').isReactive
  const isReadonly: typeof import('vue').isReadonly
  const isRef: typeof import('vue').isRef
  const isShallow: typeof import('vue').isShallow
  const locales: typeof import('./resources/js/plugins/i18n').locales
  const markRaw: typeof import('vue').markRaw
  const nextTick: typeof import('vue').nextTick
  const normalizeSchema: typeof import('./resources/js/composables/useContentSchemaState').normalizeSchema
  const normalizeSchemaField: typeof import('./resources/js/composables/useContentSchemaState').normalizeSchemaField
  const normalizeSchemaType: typeof import('./resources/js/composables/useContentSchemaState').normalizeSchemaType
  const onActivated: typeof import('vue').onActivated
  const onBeforeMount: typeof import('vue').onBeforeMount
  const onBeforeRouteLeave: typeof import('vue-router').onBeforeRouteLeave
  const onBeforeRouteUpdate: typeof import('vue-router').onBeforeRouteUpdate
  const onBeforeUnmount: typeof import('vue').onBeforeUnmount
  const onBeforeUpdate: typeof import('vue').onBeforeUpdate
  const onDeactivated: typeof import('vue').onDeactivated
  const onErrorCaptured: typeof import('vue').onErrorCaptured
  const onMounted: typeof import('vue').onMounted
  const onRenderTracked: typeof import('vue').onRenderTracked
  const onRenderTriggered: typeof import('vue').onRenderTriggered
  const onScopeDispose: typeof import('vue').onScopeDispose
  const onServerPrefetch: typeof import('vue').onServerPrefetch
  const onUnmounted: typeof import('vue').onUnmounted
  const onUpdated: typeof import('vue').onUpdated
  const onWatcherCleanup: typeof import('vue').onWatcherCleanup
  const parseTreeOperations: typeof import('./resources/js/composables/useAiContentTree').parseTreeOperations
  const provide: typeof import('vue').provide
  const queryClient: typeof import('./resources/js/plugins/vue-query').queryClient
  const queryKeys: typeof import('./resources/js/composables/useQueryClient').queryKeys
  const reactive: typeof import('vue').reactive
  const readonly: typeof import('vue').readonly
  const ref: typeof import('vue').ref
  const resolveComponent: typeof import('vue').resolveComponent
  const setAlertDialogDefaultLabels: typeof import('./resources/js/composables/useAlertDialog').setAlertDialogDefaultLabels
  const setLocale: typeof import('./resources/js/plugins/i18n').setLocale
  const shallowReactive: typeof import('vue').shallowReactive
  const shallowReadonly: typeof import('vue').shallowReadonly
  const shallowRef: typeof import('vue').shallowRef
  const toRaw: typeof import('vue').toRaw
  const toRef: typeof import('vue').toRef
  const toRefs: typeof import('vue').toRefs
  const toValue: typeof import('vue').toValue
  const triggerRef: typeof import('vue').triggerRef
  const unref: typeof import('vue').unref
  const useAiConfig: typeof import('./resources/js/composables/useAiModels').useAiConfig
  const useAiConfigs: typeof import('./resources/js/composables/useAiModels').useAiConfigs
  const useAiContent: typeof import('./resources/js/composables/useAiContent').useAiContent
  const useAiContentTree: typeof import('./resources/js/composables/useAiContentTree').useAiContentTree
  const useAiMentions: typeof import('./resources/js/composables/useAiMentions').useAiMentions
  const useAiModels: typeof import('./resources/js/composables/useAiModels').useAiModels
  const useAiSettings: typeof import('./resources/js/composables/useAiModels').useAiSettings
  const useAiTranslation: typeof import('./resources/js/composables/useAiTranslation').useAiTranslation
  const useAlertDialog: typeof import('./resources/js/composables/useAlertDialog').useAlertDialog
  const useApiClient: typeof import('./resources/js/composables/useApiClient').useApiClient
  const useAssetFolders: typeof import('./resources/js/composables/useAssetFolders').useAssetFolders
  const useAssetLibraryMoves: typeof import('./resources/js/composables/useAssetLibraryMoves').useAssetLibraryMoves
  const useAssetRequirements: typeof import('./resources/js/composables/useAssetRequirements').useAssetRequirements
  const useAssetTags: typeof import('./resources/js/composables/useAssetTags').useAssetTags
  const useAssets: typeof import('./resources/js/composables/useAssets').useAssets
  const useAttrs: typeof import('vue').useAttrs
  const useAuth: typeof import('./resources/js/composables/useAuth').useAuth
  const useAuthorization: typeof import('./resources/js/composables/useAuthorization').useAuthorization
  const useBackups: typeof import('./resources/js/composables/useBackups').useBackups
  const useBlockFolders: typeof import('./resources/js/composables/useBlockFolders').useBlockFolders
  const useBlockTags: typeof import('./resources/js/composables/useBlockTags').useBlockTags
  const useBlockTemplates: typeof import('./resources/js/composables/useBlockTemplates').useBlockTemplates
  const useBlockVersions: typeof import('./resources/js/composables/useBlockVersions').useBlockVersions
  const useBlocks: typeof import('./resources/js/composables/useBlocks').useBlocks
  const useComments: typeof import('./resources/js/composables/useComments').useComments
  const useContent: typeof import('./resources/js/composables/useContent').useContent
  const useContentJson: typeof import('./resources/js/composables/useContentJson').useContentJson
  const useContentLiveCollaboration: typeof import('./resources/js/composables/useContentLiveCollaboration').useContentLiveCollaboration
  const useContentMenu: typeof import('./resources/js/composables/useContentMenu').useContentMenu
  const useContentMenuPresence: typeof import('./resources/js/composables/useContentMenuPresence').useContentMenuPresence
  const useContentPresence: typeof import('./resources/js/composables/usePresence').useContentPresence
  const useContentSchemaState: typeof import('./resources/js/composables/useContentSchemaState').useContentSchemaState
  const useContentTree: typeof import('./resources/js/composables/useContentTree').useContentTree
  const useContentVersions: typeof import('./resources/js/composables/useContentVersions').useContentVersions
  const useContentWizardApply: typeof import('./resources/js/composables/useContentWizardApply').useContentWizardApply
  const useContentWizardCollaboration: typeof import('./resources/js/composables/useContentWizardCollaboration').useContentWizardCollaboration
  const useContentWizardKeyboard: typeof import('./resources/js/composables/useContentWizardKeyboard').useContentWizardKeyboard
  const useContentWizardLayout: typeof import('./resources/js/composables/useContentWizardLayout').useContentWizardLayout
  const useContentWizardSlug: typeof import('./resources/js/composables/useContentWizardSlug').useContentWizardSlug
  const useContentWizardTree: typeof import('./resources/js/composables/useContentWizardTree').useContentWizardTree
  const useContentWizardViewport: typeof import('./resources/js/composables/useContentWizardViewport').useContentWizardViewport
  const useCssModule: typeof import('vue').useCssModule
  const useCssVars: typeof import('vue').useCssVars
  const useDataEntries: typeof import('./resources/js/composables/useDataEntries').useDataEntries
  const useDataSources: typeof import('./resources/js/composables/useDataSources').useDataSources
  const useEcho: typeof import('./resources/js/composables/useEcho').useEcho
  const useFileUpload: typeof import('./resources/js/composables/useFileUpload').useFileUpload
  const useFileUtils: typeof import('./resources/js/composables/useFileUtils').default
  const useFormat: typeof import('./resources/js/composables/useFormat').default
  const useGlobalClipboard: typeof import('./resources/js/composables/useGlobalClipboard').useGlobalClipboard
  const useGlobalTeam: typeof import('./resources/js/composables/useGlobalTeam').useGlobalTeam
  const useHandlebars: typeof import('./resources/js/composables/useHandlebars').default
  const useI18n: typeof import('./resources/js/plugins/i18n').useI18n
  const useId: typeof import('vue').useId
  const useInvites: typeof import('./resources/js/composables/useInvites').useInvites
  const useLink: typeof import('vue-router').useLink
  const useMigrations: typeof import('./resources/js/composables/useMigrations').useMigrations
  const useModel: typeof import('vue').useModel
  const usePersonalAccessTokens: typeof import('./resources/js/composables/usePersonalAccessTokens').usePersonalAccessTokens
  const usePlans: typeof import('./resources/js/composables/usePlans').usePlans
  const usePresence: typeof import('./resources/js/composables/usePresence').usePresence
  const useRedirects: typeof import('./resources/js/composables/useRedirects').useRedirects
  const useReleases: typeof import('./resources/js/composables/useReleases').useReleases
  const useRoute: typeof import('vue-router').useRoute
  const useRouter: typeof import('vue-router').useRouter
  const useRuntimeConfig: typeof import('~/env').useRuntimeConfig
  const useSeoMeta: typeof import('./resources/js/composables/useSeoMeta').useSeoMeta
  const useSlots: typeof import('vue').useSlots
  const useSpacePresence: typeof import('./resources/js/composables/usePresence').useSpacePresence
  const useSpacePresencePeek: typeof import('./resources/js/composables/useSpacePresencePeek').useSpacePresencePeek
  const useSpaceSettings: typeof import('./resources/js/composables/useSpaceSettings').default
  const useSpaces: typeof import('./resources/js/composables/useSpace').useSpaces
  const useSubscription: typeof import('./resources/js/composables/useSubscription').useSubscription
  const useTeams: typeof import('./resources/js/composables/useTeams').useTeams
  const useTemplateRef: typeof import('vue').useTemplateRef
  const useTokens: typeof import('./resources/js/composables/useTokens').useTokens
  const useTone: typeof import('./resources/js/composables/useTone').useTone
  const useTwoFactor: typeof import('./resources/js/composables/useTwoFactor').useTwoFactor
  const useTwoFactorAuth: typeof import('./resources/js/composables/useTwoFactorAuth').useTwoFactorAuth
  const useUlid: typeof import('./resources/js/composables/useUlid').useUlid
  const useUrlNotifications: typeof import('./resources/js/composables/useUrlNotifications').useUrlNotifications
  const useUser: typeof import('./resources/js/composables/useUser').useUser
  const useUserSettings: typeof import('./resources/js/composables/useUserSettings').useUserSettings
  const watch: typeof import('vue').watch
  const watchEffect: typeof import('vue').watchEffect
  const watchPostEffect: typeof import('vue').watchPostEffect
  const watchSyncEffect: typeof import('vue').watchSyncEffect
}
// for type re-export
declare global {
  // @ts-ignore
  export type { Component, Slot, Slots, ComponentPublicInstance, ComputedRef, DirectiveBinding, ExtractDefaultPropTypes, ExtractPropTypes, ExtractPublicPropTypes, InjectionKey, PropType, Ref, ShallowRef, MaybeRef, MaybeRefOrGetter, VNode, WritableComputedRef } from 'vue'
  import('vue')
  // @ts-ignore
  export type { StreamCallbacks } from './resources/js/composables/useAiContent'
  import('./resources/js/composables/useAiContent')
  // @ts-ignore
  export type { AiContentTreeNode, CreateTreeOperation, MoveTreeOperation, UpdateTreeOperation, DeleteTreeOperation, RestoreTreeOperation, TreeOperation, ContentTreePayload, TreeOperationsResult } from './resources/js/composables/useAiContentTree'
  import('./resources/js/composables/useAiContentTree')
  // @ts-ignore
  export type { AiModel, GroupedModels, SpaceAiSettings } from './resources/js/composables/useAiModels'
  import('./resources/js/composables/useAiModels')
  // @ts-ignore
  export type { TranslationPayload } from './resources/js/composables/useAiTranslation'
  import('./resources/js/composables/useAiTranslation')
  // @ts-ignore
  export type { DialogAction, DialogOptions, MessageOptions, ConfirmOptions } from './resources/js/composables/useAlertDialog'
  import('./resources/js/composables/useAlertDialog')
  // @ts-ignore
  export type { AssetRequirementIssue } from './resources/js/composables/useAssetRequirements'
  import('./resources/js/composables/useAssetRequirements')
  // @ts-ignore
  export type { CollaborationPresenceUser, ContentFieldUpdatePayload, ContentFieldFocusPayload, ContentCommitAction } from './resources/js/composables/useContentLiveCollaboration'
  import('./resources/js/composables/useContentLiveCollaboration')
  // @ts-ignore
  export type { ContentPresenceMap } from './resources/js/composables/useContentMenuPresence'
  import('./resources/js/composables/useContentMenuPresence')
  // @ts-ignore
  export type { ContentTreeItem, FindResult } from './resources/js/composables/useContentTree'
  import('./resources/js/composables/useContentTree')
  // @ts-ignore
  export type { ClipboardSingleItem, ClipboardMultipleItems, ClipboardItem } from './resources/js/composables/useGlobalClipboard'
  import('./resources/js/composables/useGlobalClipboard')
  // @ts-ignore
  export type { PresenceUser, PresenceState, UsePresenceOptions } from './resources/js/composables/usePresence'
  import('./resources/js/composables/usePresence')
  // @ts-ignore
  export type { SeoMetaOptions } from './resources/js/composables/useSeoMeta'
  import('./resources/js/composables/useSeoMeta')
  // @ts-ignore
  export type { SpacePresenceInfo } from './resources/js/composables/useSpacePresencePeek'
  import('./resources/js/composables/useSpacePresencePeek')
  // @ts-ignore
  export type { MaybeRefOrComputed } from './resources/js/composables/useSubscription'
  import('./resources/js/composables/useSubscription')
  // @ts-ignore
  export type { MessageSchema, LocaleCode } from './resources/js/plugins/i18n'
  import('./resources/js/plugins/i18n')
}

// for vue template auto import
import { UnwrapRef } from 'vue'
declare module 'vue' {
  interface GlobalComponents {}
  interface ComponentCustomProperties {
    readonly AlertDialogProvider: UnwrapRef<typeof import('./resources/js/composables/useAlertDialog')['AlertDialogProvider']>
    readonly EffectScope: UnwrapRef<typeof import('vue')['EffectScope']>
    readonly computed: UnwrapRef<typeof import('vue')['computed']>
    readonly createApp: UnwrapRef<typeof import('vue')['createApp']>
    readonly customRef: UnwrapRef<typeof import('vue')['customRef']>
    readonly defineAsyncComponent: UnwrapRef<typeof import('vue')['defineAsyncComponent']>
    readonly defineComponent: UnwrapRef<typeof import('vue')['defineComponent']>
    readonly effectScope: UnwrapRef<typeof import('vue')['effectScope']>
    readonly extractStreamingTreeOperations: UnwrapRef<typeof import('./resources/js/composables/useAiContentTree')['extractStreamingTreeOperations']>
    readonly getCurrentInstance: UnwrapRef<typeof import('vue')['getCurrentInstance']>
    readonly getCurrentScope: UnwrapRef<typeof import('vue')['getCurrentScope']>
    readonly getCurrentWatcher: UnwrapRef<typeof import('vue')['getCurrentWatcher']>
    readonly getLocale: UnwrapRef<typeof import('./resources/js/plugins/i18n')['getLocale']>
    readonly getPosthog: UnwrapRef<typeof import('./resources/js/plugins/posthog')['getPosthog']>
    readonly h: UnwrapRef<typeof import('vue')['h']>
    readonly i18n: UnwrapRef<typeof import('./resources/js/plugins/i18n')['i18n']>
    readonly initAuth: UnwrapRef<typeof import('./resources/js/plugins/auth')['initAuth']>
    readonly inject: UnwrapRef<typeof import('vue')['inject']>
    readonly installChart: UnwrapRef<typeof import('./resources/js/plugins/chart')['installChart']>
    readonly installEcho: UnwrapRef<typeof import('./resources/js/plugins/echo')['installEcho']>
    readonly installI18n: UnwrapRef<typeof import('./resources/js/plugins/i18n')['installI18n']>
    readonly installPosthog: UnwrapRef<typeof import('./resources/js/plugins/posthog')['installPosthog']>
    readonly installVueQuery: UnwrapRef<typeof import('./resources/js/plugins/vue-query')['installVueQuery']>
    readonly isFieldVisible: UnwrapRef<typeof import('./resources/js/composables/useContentSchemaState')['isFieldVisible']>
    readonly isProxy: UnwrapRef<typeof import('vue')['isProxy']>
    readonly isReactive: UnwrapRef<typeof import('vue')['isReactive']>
    readonly isReadonly: UnwrapRef<typeof import('vue')['isReadonly']>
    readonly isRef: UnwrapRef<typeof import('vue')['isRef']>
    readonly isShallow: UnwrapRef<typeof import('vue')['isShallow']>
    readonly locales: UnwrapRef<typeof import('./resources/js/plugins/i18n')['locales']>
    readonly markRaw: UnwrapRef<typeof import('vue')['markRaw']>
    readonly nextTick: UnwrapRef<typeof import('vue')['nextTick']>
    readonly normalizeSchema: UnwrapRef<typeof import('./resources/js/composables/useContentSchemaState')['normalizeSchema']>
    readonly normalizeSchemaField: UnwrapRef<typeof import('./resources/js/composables/useContentSchemaState')['normalizeSchemaField']>
    readonly normalizeSchemaType: UnwrapRef<typeof import('./resources/js/composables/useContentSchemaState')['normalizeSchemaType']>
    readonly onActivated: UnwrapRef<typeof import('vue')['onActivated']>
    readonly onBeforeMount: UnwrapRef<typeof import('vue')['onBeforeMount']>
    readonly onBeforeRouteLeave: UnwrapRef<typeof import('vue-router')['onBeforeRouteLeave']>
    readonly onBeforeRouteUpdate: UnwrapRef<typeof import('vue-router')['onBeforeRouteUpdate']>
    readonly onBeforeUnmount: UnwrapRef<typeof import('vue')['onBeforeUnmount']>
    readonly onBeforeUpdate: UnwrapRef<typeof import('vue')['onBeforeUpdate']>
    readonly onDeactivated: UnwrapRef<typeof import('vue')['onDeactivated']>
    readonly onErrorCaptured: UnwrapRef<typeof import('vue')['onErrorCaptured']>
    readonly onMounted: UnwrapRef<typeof import('vue')['onMounted']>
    readonly onRenderTracked: UnwrapRef<typeof import('vue')['onRenderTracked']>
    readonly onRenderTriggered: UnwrapRef<typeof import('vue')['onRenderTriggered']>
    readonly onScopeDispose: UnwrapRef<typeof import('vue')['onScopeDispose']>
    readonly onServerPrefetch: UnwrapRef<typeof import('vue')['onServerPrefetch']>
    readonly onUnmounted: UnwrapRef<typeof import('vue')['onUnmounted']>
    readonly onUpdated: UnwrapRef<typeof import('vue')['onUpdated']>
    readonly onWatcherCleanup: UnwrapRef<typeof import('vue')['onWatcherCleanup']>
    readonly parseTreeOperations: UnwrapRef<typeof import('./resources/js/composables/useAiContentTree')['parseTreeOperations']>
    readonly provide: UnwrapRef<typeof import('vue')['provide']>
    readonly queryClient: UnwrapRef<typeof import('./resources/js/plugins/vue-query')['queryClient']>
    readonly queryKeys: UnwrapRef<typeof import('./resources/js/composables/useQueryClient')['queryKeys']>
    readonly reactive: UnwrapRef<typeof import('vue')['reactive']>
    readonly readonly: UnwrapRef<typeof import('vue')['readonly']>
    readonly ref: UnwrapRef<typeof import('vue')['ref']>
    readonly resolveComponent: UnwrapRef<typeof import('vue')['resolveComponent']>
    readonly setAlertDialogDefaultLabels: UnwrapRef<typeof import('./resources/js/composables/useAlertDialog')['setAlertDialogDefaultLabels']>
    readonly setLocale: UnwrapRef<typeof import('./resources/js/plugins/i18n')['setLocale']>
    readonly shallowReactive: UnwrapRef<typeof import('vue')['shallowReactive']>
    readonly shallowReadonly: UnwrapRef<typeof import('vue')['shallowReadonly']>
    readonly shallowRef: UnwrapRef<typeof import('vue')['shallowRef']>
    readonly toRaw: UnwrapRef<typeof import('vue')['toRaw']>
    readonly toRef: UnwrapRef<typeof import('vue')['toRef']>
    readonly toRefs: UnwrapRef<typeof import('vue')['toRefs']>
    readonly toValue: UnwrapRef<typeof import('vue')['toValue']>
    readonly triggerRef: UnwrapRef<typeof import('vue')['triggerRef']>
    readonly unref: UnwrapRef<typeof import('vue')['unref']>
    readonly useAiConfigs: UnwrapRef<typeof import('./resources/js/composables/useAiModels')['useAiConfigs']>
    readonly useAiContent: UnwrapRef<typeof import('./resources/js/composables/useAiContent')['useAiContent']>
    readonly useAiContentTree: UnwrapRef<typeof import('./resources/js/composables/useAiContentTree')['useAiContentTree']>
    readonly useAiMentions: UnwrapRef<typeof import('./resources/js/composables/useAiMentions')['useAiMentions']>
    readonly useAiModels: UnwrapRef<typeof import('./resources/js/composables/useAiModels')['useAiModels']>
    readonly useAiSettings: UnwrapRef<typeof import('./resources/js/composables/useAiModels')['useAiSettings']>
    readonly useAiTranslation: UnwrapRef<typeof import('./resources/js/composables/useAiTranslation')['useAiTranslation']>
    readonly useAlertDialog: UnwrapRef<typeof import('./resources/js/composables/useAlertDialog')['useAlertDialog']>
    readonly useApiClient: UnwrapRef<typeof import('./resources/js/composables/useApiClient')['useApiClient']>
    readonly useAssetFolders: UnwrapRef<typeof import('./resources/js/composables/useAssetFolders')['useAssetFolders']>
    readonly useAssetLibraryMoves: UnwrapRef<typeof import('./resources/js/composables/useAssetLibraryMoves')['useAssetLibraryMoves']>
    readonly useAssetRequirements: UnwrapRef<typeof import('./resources/js/composables/useAssetRequirements')['useAssetRequirements']>
    readonly useAssetTags: UnwrapRef<typeof import('./resources/js/composables/useAssetTags')['useAssetTags']>
    readonly useAssets: UnwrapRef<typeof import('./resources/js/composables/useAssets')['useAssets']>
    readonly useAttrs: UnwrapRef<typeof import('vue')['useAttrs']>
    readonly useAuth: UnwrapRef<typeof import('./resources/js/composables/useAuth')['useAuth']>
    readonly useAuthorization: UnwrapRef<typeof import('./resources/js/composables/useAuthorization')['useAuthorization']>
    readonly useBackups: UnwrapRef<typeof import('./resources/js/composables/useBackups')['useBackups']>
    readonly useBlockFolders: UnwrapRef<typeof import('./resources/js/composables/useBlockFolders')['useBlockFolders']>
    readonly useBlockTags: UnwrapRef<typeof import('./resources/js/composables/useBlockTags')['useBlockTags']>
    readonly useBlockTemplates: UnwrapRef<typeof import('./resources/js/composables/useBlockTemplates')['useBlockTemplates']>
    readonly useBlockVersions: UnwrapRef<typeof import('./resources/js/composables/useBlockVersions')['useBlockVersions']>
    readonly useBlocks: UnwrapRef<typeof import('./resources/js/composables/useBlocks')['useBlocks']>
    readonly useComments: UnwrapRef<typeof import('./resources/js/composables/useComments')['useComments']>
    readonly useContent: UnwrapRef<typeof import('./resources/js/composables/useContent')['useContent']>
    readonly useContentJson: UnwrapRef<typeof import('./resources/js/composables/useContentJson')['useContentJson']>
    readonly useContentLiveCollaboration: UnwrapRef<typeof import('./resources/js/composables/useContentLiveCollaboration')['useContentLiveCollaboration']>
    readonly useContentMenu: UnwrapRef<typeof import('./resources/js/composables/useContentMenu')['useContentMenu']>
    readonly useContentMenuPresence: UnwrapRef<typeof import('./resources/js/composables/useContentMenuPresence')['useContentMenuPresence']>
    readonly useContentPresence: UnwrapRef<typeof import('./resources/js/composables/usePresence')['useContentPresence']>
    readonly useContentSchemaState: UnwrapRef<typeof import('./resources/js/composables/useContentSchemaState')['useContentSchemaState']>
    readonly useContentTree: UnwrapRef<typeof import('./resources/js/composables/useContentTree')['useContentTree']>
    readonly useContentVersions: UnwrapRef<typeof import('./resources/js/composables/useContentVersions')['useContentVersions']>
    readonly useContentWizardApply: UnwrapRef<typeof import('./resources/js/composables/useContentWizardApply')['useContentWizardApply']>
    readonly useContentWizardCollaboration: UnwrapRef<typeof import('./resources/js/composables/useContentWizardCollaboration')['useContentWizardCollaboration']>
    readonly useContentWizardKeyboard: UnwrapRef<typeof import('./resources/js/composables/useContentWizardKeyboard')['useContentWizardKeyboard']>
    readonly useContentWizardLayout: UnwrapRef<typeof import('./resources/js/composables/useContentWizardLayout')['useContentWizardLayout']>
    readonly useContentWizardSlug: UnwrapRef<typeof import('./resources/js/composables/useContentWizardSlug')['useContentWizardSlug']>
    readonly useContentWizardTree: UnwrapRef<typeof import('./resources/js/composables/useContentWizardTree')['useContentWizardTree']>
    readonly useContentWizardViewport: UnwrapRef<typeof import('./resources/js/composables/useContentWizardViewport')['useContentWizardViewport']>
    readonly useCssModule: UnwrapRef<typeof import('vue')['useCssModule']>
    readonly useCssVars: UnwrapRef<typeof import('vue')['useCssVars']>
    readonly useDataEntries: UnwrapRef<typeof import('./resources/js/composables/useDataEntries')['useDataEntries']>
    readonly useDataSources: UnwrapRef<typeof import('./resources/js/composables/useDataSources')['useDataSources']>
    readonly useEcho: UnwrapRef<typeof import('./resources/js/composables/useEcho')['useEcho']>
    readonly useFileUpload: UnwrapRef<typeof import('./resources/js/composables/useFileUpload')['useFileUpload']>
    readonly useFileUtils: UnwrapRef<typeof import('./resources/js/composables/useFileUtils')['default']>
    readonly useFormat: UnwrapRef<typeof import('./resources/js/composables/useFormat')['default']>
    readonly useGlobalClipboard: UnwrapRef<typeof import('./resources/js/composables/useGlobalClipboard')['useGlobalClipboard']>
    readonly useGlobalTeam: UnwrapRef<typeof import('./resources/js/composables/useGlobalTeam')['useGlobalTeam']>
    readonly useHandlebars: UnwrapRef<typeof import('./resources/js/composables/useHandlebars')['default']>
    readonly useI18n: UnwrapRef<typeof import('./resources/js/plugins/i18n')['useI18n']>
    readonly useId: UnwrapRef<typeof import('vue')['useId']>
    readonly useInvites: UnwrapRef<typeof import('./resources/js/composables/useInvites')['useInvites']>
    readonly useLink: UnwrapRef<typeof import('vue-router')['useLink']>
    readonly useMigrations: UnwrapRef<typeof import('./resources/js/composables/useMigrations')['useMigrations']>
    readonly useModel: UnwrapRef<typeof import('vue')['useModel']>
    readonly usePersonalAccessTokens: UnwrapRef<typeof import('./resources/js/composables/usePersonalAccessTokens')['usePersonalAccessTokens']>
    readonly usePlans: UnwrapRef<typeof import('./resources/js/composables/usePlans')['usePlans']>
    readonly usePresence: UnwrapRef<typeof import('./resources/js/composables/usePresence')['usePresence']>
    readonly useRedirects: UnwrapRef<typeof import('./resources/js/composables/useRedirects')['useRedirects']>
    readonly useReleases: UnwrapRef<typeof import('./resources/js/composables/useReleases')['useReleases']>
    readonly useRoute: UnwrapRef<typeof import('vue-router')['useRoute']>
    readonly useRouter: UnwrapRef<typeof import('vue-router')['useRouter']>
    readonly useRuntimeConfig: UnwrapRef<typeof import('~/env')['useRuntimeConfig']>
    readonly useSeoMeta: UnwrapRef<typeof import('./resources/js/composables/useSeoMeta')['useSeoMeta']>
    readonly useSlots: UnwrapRef<typeof import('vue')['useSlots']>
    readonly useSpacePresence: UnwrapRef<typeof import('./resources/js/composables/usePresence')['useSpacePresence']>
    readonly useSpacePresencePeek: UnwrapRef<typeof import('./resources/js/composables/useSpacePresencePeek')['useSpacePresencePeek']>
    readonly useSpaceSettings: UnwrapRef<typeof import('./resources/js/composables/useSpaceSettings')['default']>
    readonly useSpaces: UnwrapRef<typeof import('./resources/js/composables/useSpace')['useSpaces']>
    readonly useSubscription: UnwrapRef<typeof import('./resources/js/composables/useSubscription')['useSubscription']>
    readonly useTeams: UnwrapRef<typeof import('./resources/js/composables/useTeams')['useTeams']>
    readonly useTemplateRef: UnwrapRef<typeof import('vue')['useTemplateRef']>
    readonly useTokens: UnwrapRef<typeof import('./resources/js/composables/useTokens')['useTokens']>
    readonly useTone: UnwrapRef<typeof import('./resources/js/composables/useTone')['useTone']>
    readonly useTwoFactor: UnwrapRef<typeof import('./resources/js/composables/useTwoFactor')['useTwoFactor']>
    readonly useTwoFactorAuth: UnwrapRef<typeof import('./resources/js/composables/useTwoFactorAuth')['useTwoFactorAuth']>
    readonly useUlid: UnwrapRef<typeof import('./resources/js/composables/useUlid')['useUlid']>
    readonly useUrlNotifications: UnwrapRef<typeof import('./resources/js/composables/useUrlNotifications')['useUrlNotifications']>
    readonly useUser: UnwrapRef<typeof import('./resources/js/composables/useUser')['useUser']>
    readonly useUserSettings: UnwrapRef<typeof import('./resources/js/composables/useUserSettings')['useUserSettings']>
    readonly watch: UnwrapRef<typeof import('vue')['watch']>
    readonly watchEffect: UnwrapRef<typeof import('vue')['watchEffect']>
    readonly watchPostEffect: UnwrapRef<typeof import('vue')['watchPostEffect']>
    readonly watchSyncEffect: UnwrapRef<typeof import('vue')['watchSyncEffect']>
  }
}