import { fileURLToPath } from 'node:url'

import vue from '@vitejs/plugin-vue'
import AutoImport from 'unplugin-auto-import/vite'
import { defineConfig } from 'vitest/config'

const sourceDir = fileURLToPath(new URL('./resources/js', import.meta.url))

// Deliberately not `mergeConfig(viteConfig, …)`: the app config pulls in the
// Laravel, Tailwind and PWA plugins, which need a running dev server / build
// pipeline. Tests only need the pieces that change how modules resolve and
// compile — the alias, the Vue SFC compiler and the auto-imports that
// composables and components rely on at authoring time.
export default defineConfig({
  plugins: [
    AutoImport({
      imports: [
        'vue',
        'vue-router',
        {
          '~/env': ['useRuntimeConfig'],
        },
      ],
      // The checked-in d.ts is generated by the app config; regenerating it
      // from the (smaller) test config would churn it on every test run.
      dts: false,
      dirs: ['resources/js/composables', 'resources/js/plugins'],
      vueTemplate: true,
    }),
    vue(),
  ],
  resolve: {
    alias: {
      '~': sourceDir,
      '@': sourceDir,
    },
  },
  test: {
    // jsdom rather than happy-dom: `~/lib/sanitize` runs DOMPurify, and
    // happy-dom's parser mangles the fragments enough that sanitization
    // silently no-ops — a security helper must be tested on a faithful DOM.
    environment: 'jsdom',
    // No globals: every test imports describe/it/expect explicitly, so the
    // checked-in tsconfig needs no extra ambient types to typecheck them.
    include: ['tests/js/**/*.test.ts'],
    setupFiles: ['tests/js/setup.ts'],
    coverage: {
      provider: 'v8',
      include: ['resources/js/lib/**', 'resources/js/utils/**', 'resources/js/composables/**'],
      reporter: ['text', 'html'],
    },
  },
})
