<?php

return [
    'mode' => env('AI_MODE', 'space'),

    'default' => env('AI_DEFAULT_DRIVER', 'openrouter'),

    'drivers' => [
        'openai' => [
            'enabled' => env('OPENAI_ENABLED', false),
            'api_key' => env('OPENAI_API_KEY'),
            'organization' => env('OPENAI_ORGANIZATION'),
            'models' => [
                [
                    'id' => 'gpt-4o',
                    'name' => 'GPT-4o',
                    'description' => 'Most capable GPT-4 model, optimized for speed and intelligence',
                    'context_window' => ['input' => 128000, 'output' => 16384],
                    'input_cost' => 2.50,
                    'output_cost' => 10.00,
                    'capabilities' => ['text', 'vision', 'tools'],
                    'supports_streaming' => true,
                    'supports_tools' => true,
                    'supports_vision' => true,
                ],
                [
                    'id' => 'gpt-4o-mini',
                    'name' => 'GPT-4o Mini',
                    'description' => 'Affordable and intelligent small model for fast tasks',
                    'context_window' => ['input' => 128000, 'output' => 16384],
                    'input_cost' => 0.15,
                    'output_cost' => 0.60,
                    'capabilities' => ['text', 'vision', 'tools'],
                    'supports_streaming' => true,
                    'supports_tools' => true,
                    'supports_vision' => true,
                ],
                [
                    'id' => 'gpt-4-turbo',
                    'name' => 'GPT-4 Turbo',
                    'description' => 'Previous generation GPT-4 with vision capabilities',
                    'context_window' => ['input' => 128000, 'output' => 4096],
                    'input_cost' => 10.00,
                    'output_cost' => 30.00,
                    'capabilities' => ['text', 'vision', 'tools'],
                    'supports_streaming' => true,
                    'supports_tools' => true,
                    'supports_vision' => true,
                ],
                [
                    'id' => 'o1',
                    'name' => 'o1',
                    'description' => 'Reasoning model for complex problem-solving',
                    'context_window' => ['input' => 200000, 'output' => 100000],
                    'input_cost' => 15.00,
                    'output_cost' => 60.00,
                    'capabilities' => ['text', 'reasoning'],
                    'supports_streaming' => true,
                    'supports_tools' => false,
                    'supports_vision' => false,
                ],
                [
                    'id' => 'o1-mini',
                    'name' => 'o1 Mini',
                    'description' => 'Fast and affordable reasoning model',
                    'context_window' => ['input' => 128000, 'output' => 65536],
                    'input_cost' => 1.10,
                    'output_cost' => 4.40,
                    'capabilities' => ['text', 'reasoning'],
                    'supports_streaming' => true,
                    'supports_tools' => false,
                    'supports_vision' => false,
                ],
            ],
        ],

        'bedrock' => [
            'enabled' => env('BEDROCK_ENABLED', false),
            'region' => env('AWS_DEFAULT_REGION', 'us-east-1'),
            'key' => env('AWS_ACCESS_KEY_ID'),
            'secret' => env('AWS_SECRET_ACCESS_KEY'),
            'models' => [
                [
                    'id' => 'anthropic.claude-3-5-sonnet-20241022-v2:0',
                    'name' => 'Claude 3.5 Sonnet v2',
                    'description' => 'Anthropic\'s most intelligent model',
                    'context_window' => ['input' => 200000, 'output' => 8192],
                    'input_cost' => 3.00,
                    'output_cost' => 15.00,
                    'capabilities' => ['text', 'vision', 'tools'],
                    'supports_streaming' => true,
                    'supports_tools' => true,
                    'supports_vision' => true,
                ],
                [
                    'id' => 'anthropic.claude-3-5-haiku-20241022-v1:0',
                    'name' => 'Claude 3.5 Haiku',
                    'description' => 'Fast and efficient model for everyday tasks',
                    'context_window' => ['input' => 200000, 'output' => 8192],
                    'input_cost' => 0.25,
                    'output_cost' => 1.25,
                    'capabilities' => ['text', 'vision', 'tools'],
                    'supports_streaming' => true,
                    'supports_tools' => true,
                    'supports_vision' => true,
                ],
                [
                    'id' => 'anthropic.claude-3-opus-20240229-v1:0',
                    'name' => 'Claude 3 Opus',
                    'description' => 'Powerful model for complex tasks',
                    'context_window' => ['input' => 200000, 'output' => 4096],
                    'input_cost' => 15.00,
                    'output_cost' => 75.00,
                    'capabilities' => ['text', 'vision', 'tools'],
                    'supports_streaming' => true,
                    'supports_tools' => true,
                    'supports_vision' => true,
                ],
            ],
        ],

        'openrouter' => [
            'enabled' => env('OPENROUTER_ENABLED', false),
            'api_key' => env('OPENROUTER_API_KEY'),
            'management_key' => env('OPENROUTER_MANAGEMENT_KEY'),
            'site_url' => env('OPENROUTER_SITE_URL', config('app.url')),
            'site_name' => env('OPENROUTER_SITE_NAME', config('app.name')),
            'models' => [],
            'provision_demo_keys' => env('OPENROUTER_PROVISION_DEMO_KEYS', true),
            'demo_key_limit' => env('OPENROUTER_DEMO_KEY_LIMIT', 2.0),
            'demo_key_expiry_days' => env('OPENROUTER_DEMO_KEY_EXPIRY_DAYS', 30),
        ],
    ],

    'cache' => [
        'models_ttl' => env('AI_MODELS_CACHE_TTL', 43200),
    ],
];
