<?php

return [
    'cache_ttl_seconds' => 3600,

    'cache_key_prefix' => 'authz:user:',

    'team_abilities' => [
        'team.view',
        'team.update',
        'team.delete',
        'team.members.view',
        'team.members.manage',
        'team.invites.view',
        'team.invites.manage',
        'team.saml.manage',
        'team.spaces.create',
        'team.children.view',
        'team.children.manage',
    ],

    'space_abilities' => [
        'space.view',
        'space.update',
        'space.archive',
        'space.delete',
        'space.members.view',
        'space.members.manage',
        'space.invites.view',
        'space.invites.manage',
        'space.billing.view',
        'space.billing.manage',
        'space.tokens.view',
        'space.tokens.manage',
        'assets.view',
        'assets.manage',
        'asset_folders.view',
        'asset_folders.manage',
        'asset_tags.view',
        'asset_tags.manage',
        'blocks.view',
        'blocks.manage',
        'block_templates.view',
        'block_templates.manage',
        'block_versions.view',
        'block_versions.manage',
        'content.view',
        'content.manage',
        'content.publish',
        'content.history.view',
        'comments.view',
        'comments.create',
        'comments.update_own',
        'comments.delete_own',
        'comments.resolve_own',
        'comments.react',
        'data_sources.view',
        'data_sources.manage',
        'data_entries.view',
        'data_entries.manage',
        'redirects.view',
        'redirects.manage',
        'releases.view',
        'releases.manage',
        'releases.publish',
        'backups.view',
        'backups.manage',
        'migrations.view',
        'migrations.manage',
        'ai.view',
        'ai.manage',
        'audit_logs.view',
    ],

    'roles' => [
        'team' => [
            'owner' => [
                'name' => 'Owner',
                'description' => 'Full control of the team and its structure.',
                'level' => 300,
                'abilities' => [
                    'team.view',
                    'team.update',
                    'team.delete',
                    'team.members.view',
                    'team.members.manage',
                    'team.invites.view',
                    'team.invites.manage',
                    'team.saml.manage',
                    'team.spaces.create',
                    'team.children.view',
                    'team.children.manage',
                ],
            ],
            'admin' => [
                'name' => 'Admin',
                'description' => 'Manage members, invites, and spaces for the team.',
                'level' => 200,
                'abilities' => [
                    'team.view',
                    'team.update',
                    'team.members.view',
                    'team.members.manage',
                    'team.invites.view',
                    'team.invites.manage',
                    'team.spaces.create',
                    'team.children.view',
                    'team.children.manage',
                ],
            ],
            'member' => [
                'name' => 'Member',
                'description' => 'Basic visibility into the team.',
                'level' => 100,
                'abilities' => [
                    'team.view',
                ],
            ],
        ],
        'space' => [
            'owner' => [
                'name' => 'Owner',
                'description' => 'Full control of the space.',
                'level' => 300,
                'abilities' => [
                    'space.view',
                    'space.update',
                    'space.archive',
                    'space.delete',
                    'space.members.view',
                    'space.members.manage',
                    'space.invites.view',
                    'space.invites.manage',
                    'space.billing.view',
                    'space.billing.manage',
                    'space.tokens.view',
                    'space.tokens.manage',
                    'assets.view',
                    'assets.manage',
                    'asset_folders.view',
                    'asset_folders.manage',
                    'asset_tags.view',
                    'asset_tags.manage',
                    'blocks.view',
                    'blocks.manage',
                    'block_templates.view',
                    'block_templates.manage',
                    'block_versions.view',
                    'block_versions.manage',
                    'content.view',
                    'content.manage',
                    'content.publish',
                    'content.history.view',
                    'comments.view',
                    'comments.create',
                    'comments.update_own',
                    'comments.delete_own',
                    'comments.resolve_own',
                    'comments.react',
                    'data_sources.view',
                    'data_sources.manage',
                    'data_entries.view',
                    'data_entries.manage',
                    'redirects.view',
                    'redirects.manage',
                    'releases.view',
                    'releases.manage',
                    'releases.publish',
                    'backups.view',
                    'backups.manage',
                    'migrations.view',
                    'migrations.manage',
                    'ai.view',
                    'ai.manage',
                    'audit_logs.view',
                ],
            ],
            'admin' => [
                'name' => 'Admin',
                'description' => 'Administrative control of the space.',
                'level' => 200,
                'abilities' => [
                    'space.view',
                    'space.update',
                    'space.members.view',
                    'space.members.manage',
                    'space.invites.view',
                    'space.invites.manage',
                    'space.billing.view',
                    'space.billing.manage',
                    'space.tokens.view',
                    'space.tokens.manage',
                    'assets.view',
                    'assets.manage',
                    'asset_folders.view',
                    'asset_folders.manage',
                    'asset_tags.view',
                    'asset_tags.manage',
                    'blocks.view',
                    'blocks.manage',
                    'block_templates.view',
                    'block_templates.manage',
                    'block_versions.view',
                    'block_versions.manage',
                    'content.view',
                    'content.manage',
                    'content.publish',
                    'content.history.view',
                    'comments.view',
                    'comments.create',
                    'comments.update_own',
                    'comments.delete_own',
                    'comments.resolve_own',
                    'comments.react',
                    'data_sources.view',
                    'data_sources.manage',
                    'data_entries.view',
                    'data_entries.manage',
                    'redirects.view',
                    'redirects.manage',
                    'releases.view',
                    'releases.manage',
                    'releases.publish',
                    'backups.view',
                    'backups.manage',
                    'migrations.view',
                    'migrations.manage',
                    'ai.view',
                    'ai.manage',
                    'audit_logs.view',
                ],
            ],
            'editor' => [
                'name' => 'Editor',
                'description' => 'Editorial and structured content management.',
                'level' => 150,
                'abilities' => [
                    'space.view',
                    'content.view',
                    'content.manage',
                    'content.publish',
                    'content.history.view',
                    'comments.view',
                    'comments.create',
                    'comments.update_own',
                    'comments.delete_own',
                    'comments.resolve_own',
                    'comments.react',
                    'data_sources.view',
                    'data_entries.view',
                    'data_entries.manage',
                    'redirects.view',
                    'redirects.manage',
                    'releases.view',
                    'releases.manage',
                    'releases.publish',
                    'assets.view',
                    'blocks.view',
                    'block_templates.view',
                    'block_versions.view',
                    'asset_folders.view',
                    'asset_tags.view',
                    'audit_logs.view',
                ],
            ],
            'member' => [
                'name' => 'Member',
                'description' => 'Collaborative access for content and comments.',
                'level' => 120,
                'abilities' => [
                    'space.view',
                    'content.view',
                    'content.manage',
                    'content.publish',
                    'content.history.view',
                    'comments.view',
                    'comments.create',
                    'comments.update_own',
                    'comments.delete_own',
                    'comments.resolve_own',
                    'comments.react',
                    'data_sources.view',
                    'data_entries.view',
                    'redirects.view',
                    'releases.view',
                    'assets.view',
                    'blocks.view',
                    'block_templates.view',
                    'block_versions.view',
                    'asset_folders.view',
                    'asset_tags.view',
                ],
            ],
            'viewer' => [
                'name' => 'Viewer',
                'description' => 'Read-only access to the space.',
                'level' => 100,
                'abilities' => [
                    'space.view',
                    'assets.view',
                    'asset_folders.view',
                    'asset_tags.view',
                    'blocks.view',
                    'block_templates.view',
                    'block_versions.view',
                    'content.view',
                    'content.history.view',
                    'comments.view',
                    'comments.react',
                    'data_sources.view',
                    'data_entries.view',
                    'redirects.view',
                    'releases.view',
                    'backups.view',
                    'migrations.view',
                    'ai.view',
                ],
            ],
        ],
    ],

    'team_space_abilities' => [
        'owner' => [
            'space.view',
            'space.update',
            'space.archive',
            'space.delete',
            'space.members.view',
            'space.members.manage',
            'space.invites.view',
            'space.invites.manage',
            'space.billing.view',
            'space.billing.manage',
            'space.tokens.view',
            'space.tokens.manage',
        ],
        'admin' => [
            'space.view',
        ],
        'member' => [
            'space.view',
        ],
    ],

    'legacy_mappings' => [
        'team' => [
            'guest' => 'member',
        ],
        'remove_team_roles' => [
            'space',
        ],
    ],
];
