<?php

declare(strict_types=1);

// Generated from @b10cks/mcp-server operations.ts + @b10cks/mgmt-client.
// Placeholders in `uri` are MCP argument names; {blockId}-style placeholders
// fall back to the generic {id} argument at dispatch time.

return [
    // ─── System ─────────────────────────────────────────────────────────────────
    'system.health' => [
        'description' => 'Check Management API health.',
        'method' => 'GET',
        'uri' => '/mgmt/v1/health',
    ],
    'system.config' => [
        'description' => 'Read public Management API configuration.',
        'method' => 'GET',
        'uri' => '/mgmt/v1/config',
    ],

    // ─── Users ──────────────────────────────────────────────────────────────────
    'users.me' => [
        'description' => 'Read the authenticated user.',
        'method' => 'GET',
        'uri' => '/mgmt/v1/users/me',
    ],
    'users.updateMe' => [
        'description' => 'Update the authenticated user profile.',
        'required' => ['payload'],
        'accepts' => ['payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/users/me',
    ],

    // ─── Teams ──────────────────────────────────────────────────────────────────
    'teams.list' => [
        'description' => 'List teams.',
        'accepts' => ['params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/teams',
    ],
    'teams.create' => [
        'description' => 'Create a team.',
        'required' => ['payload'],
        'accepts' => ['payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/teams',
    ],
    'teams.get' => [
        'description' => 'Get a team by ID.',
        'required' => ['teamId'],
        'accepts' => ['teamId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/teams/{teamId}',
    ],
    'teams.update' => [
        'description' => 'Update a team.',
        'required' => ['teamId', 'payload'],
        'accepts' => ['teamId', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/teams/{teamId}',
    ],
    'teams.delete' => [
        'description' => 'Delete a team.',
        'required' => ['teamId'],
        'accepts' => ['teamId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/teams/{teamId}',
    ],
    'teams.hierarchy' => [
        'description' => 'Read team hierarchy.',
        'method' => 'GET',
        'uri' => '/mgmt/v1/teams/hierarchy',
    ],
    'teams.addUser' => [
        'description' => 'Add a user to a team.',
        'required' => ['teamId', 'payload'],
        'accepts' => ['teamId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/teams/{teamId}/users',
    ],
    'teams.removeUser' => [
        'description' => 'Remove a user from a team.',
        'required' => ['teamId', 'userId'],
        'accepts' => ['teamId', 'userId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/teams/{teamId}/users/{userId}',
    ],

    // ─── Spaces ─────────────────────────────────────────────────────────────────
    'spaces.list' => [
        'description' => 'List spaces.',
        'accepts' => ['params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces',
    ],
    'spaces.create' => [
        'description' => 'Create a space.',
        'required' => ['payload'],
        'accepts' => ['payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces',
    ],
    'spaces.get' => [
        'description' => 'Get a space by ID.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}',
    ],
    'spaces.update' => [
        'description' => 'Update a space.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}',
    ],
    'spaces.delete' => [
        'description' => 'Delete a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}',
    ],
    'spaces.updateIcon' => [
        'description' => 'Update a space icon.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/icon',
    ],
    'spaces.archive' => [
        'description' => 'Archive a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/archive',
    ],
    'spaces.aiUsage' => [
        'description' => 'Read AI usage for a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/ai-usage',
    ],
    'spaces.stats' => [
        'description' => 'Read stats for a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/stats',
    ],
    'spaces.contentMenu' => [
        'description' => 'Get the content menu (site structure tree) for a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/content-menu',
    ],
    // Members
    'spaces.listMembers' => [
        'description' => 'List members of a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/members',
    ],
    'spaces.updateMember' => [
        'description' => 'Update a space member role.',
        'required' => ['spaceId', 'userId', 'payload'],
        'accepts' => ['spaceId', 'userId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/spaces/{spaceId}/members/{userId}',
    ],
    'spaces.removeMember' => [
        'description' => 'Remove a member from a space.',
        'required' => ['spaceId', 'userId'],
        'accepts' => ['spaceId', 'userId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/members/{userId}',
    ],
    // Invites
    'spaces.listInvites' => [
        'description' => 'List pending invites for a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/invites',
    ],
    'spaces.createInvite' => [
        'description' => 'Invite a user to a space.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/invites',
    ],
    'spaces.deleteInvite' => [
        'description' => 'Delete a pending space invite.',
        'required' => ['spaceId', 'inviteId'],
        'accepts' => ['spaceId', 'inviteId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/invites/{inviteId}',
    ],
    'spaces.resendInvite' => [
        'description' => 'Resend a space invite email.',
        'required' => ['spaceId', 'inviteId'],
        'accepts' => ['spaceId', 'inviteId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/invites/{inviteId}/resend',
    ],
    // Search
    'spaces.updateSearch' => [
        'description' => 'Update search configuration for a space.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/spaces/{spaceId}/search',
    ],
    'spaces.reindexSearch' => [
        'description' => 'Trigger a full search reindex for a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/search/reindex',
    ],
    // Subscriptions
    'spaces.listSubscriptions' => [
        'description' => 'List subscription plans available for a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/subscriptions',
    ],
    'spaces.getCurrentSubscription' => [
        'description' => 'Get the current active subscription of a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/subscriptions/current',
    ],
    'spaces.checkoutSubscription' => [
        'description' => 'Create a checkout session to upgrade/change a space subscription.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/subscriptions/checkout',
    ],
    'spaces.reinitSubscription' => [
        'description' => 'Reinitialize a space subscription (get a new checkout URL).',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/subscriptions/reinit',
    ],
    'spaces.cancelSubscription' => [
        'description' => 'Cancel the active subscription for a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/subscriptions/cancel',
    ],
    'spaces.resumeSubscription' => [
        'description' => 'Resume a subscription that is scheduled for cancellation.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/subscriptions/resume',
    ],
    'spaces.deletePendingSubscription' => [
        'description' => 'Discard the pending (not yet paid) subscription of a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/subscriptions/pending',
    ],
    'spaces.getPlanProposal' => [
        'description' => 'Get the current open payment request (proposed plan handed to a billing contact), if any.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/subscriptions/proposal',
    ],
    'spaces.createPlanProposal' => [
        'description' => 'Create a payment request: propose a plan and hand the checkout to a billing contact. Replaces any previous open one.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/subscriptions/proposal',
    ],
    'spaces.deletePlanProposal' => [
        'description' => 'Revoke the current open payment request.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/subscriptions/proposal',
    ],
    'spaces.listPlans' => [
        'description' => 'List the plans available to a space, including custom agency plans.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/plans',
    ],
    'spaces.listPeople' => [
        'description' => 'List people of a space: members and pending invites in one directory. Params: q, sort, page, per_page.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/people',
    ],
    // AI Settings
    'spaces.getAiSettings' => [
        'description' => 'Get AI settings for a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/ai-settings',
    ],
    'spaces.updateAiSettings' => [
        'description' => 'Update AI settings for a space.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/spaces/{spaceId}/ai-settings',
    ],
    // AI Configs
    'spaces.listAiConfigs' => [
        'description' => 'List AI configurations for a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/ai-configs',
    ],
    'spaces.createAiConfig' => [
        'description' => 'Create an AI configuration for a space.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/ai-configs',
    ],
    'spaces.getAiConfig' => [
        'description' => 'Get an AI configuration by ID.',
        'required' => ['spaceId', 'configId'],
        'accepts' => ['spaceId', 'configId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/ai-configs/{configId}',
    ],
    'spaces.updateAiConfig' => [
        'description' => 'Update an AI configuration.',
        'required' => ['spaceId', 'configId', 'payload'],
        'accepts' => ['spaceId', 'configId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/spaces/{spaceId}/ai-configs/{configId}',
    ],
    'spaces.deleteAiConfig' => [
        'description' => 'Delete an AI configuration.',
        'required' => ['spaceId', 'configId'],
        'accepts' => ['spaceId', 'configId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/ai-configs/{configId}',
    ],
    // Audit Logs
    'spaces.getAuditLogs' => [
        'description' => 'Get audit logs for a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/audit-logs',
    ],
    // Backups
    'spaces.listBackups' => [
        'description' => 'List backups for a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/backups',
    ],
    'spaces.createBackup' => [
        'description' => 'Create a backup for a space.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/backups',
    ],
    'spaces.getBackup' => [
        'description' => 'Get a backup by ID.',
        'required' => ['spaceId', 'backupId'],
        'accepts' => ['spaceId', 'backupId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/backups/{backupId}',
    ],
    'spaces.updateBackup' => [
        'description' => 'Update a backup.',
        'required' => ['spaceId', 'backupId', 'payload'],
        'accepts' => ['spaceId', 'backupId', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/backups/{backupId}',
    ],
    'spaces.deleteBackup' => [
        'description' => 'Delete a backup.',
        'required' => ['spaceId', 'backupId'],
        'accepts' => ['spaceId', 'backupId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/backups/{backupId}',
    ],
    // Migrations
    'spaces.listMigrations' => [
        'description' => 'List migrations for a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/migrations',
    ],
    'spaces.createMigration' => [
        'description' => 'Create a migration for a space.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/migrations',
    ],

    // ─── Blocks ─────────────────────────────────────────────────────────────────
    'blocks.list' => [
        'description' => 'List block definitions in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks',
    ],
    'blocks.create' => [
        'description' => 'Create a block definition. Payload fields: name (string), slug (string, unique), type ("root"|"nestable"|"single"), schema (object mapping field keys to field definitions), editor (array of {header, items} tab groups), tags (string[]), icon (string), color (hex string), preview_template (mustache string). Call b10cks_content_model_guide first for field type options, tag hierarchy, and canonical patterns.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks',
    ],
    'blocks.get' => [
        'description' => 'Get a block definition by ID.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'blockId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks/{blockId}',
    ],
    'blocks.update' => [
        'description' => 'Update a block definition. Same payload structure as blocks.create — only include fields to change. Schema field keys are stable identifiers; renaming a key creates a new field and loses existing data.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'blockId', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks/{blockId}',
    ],
    'blocks.delete' => [
        'description' => 'Delete a block definition.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'blockId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks/{blockId}',
    ],
    'blocks.sync' => [
        'description' => 'Reconcile a full set of block definitions against the space in one transaction. Payload: blocks (array of complete block definitions, each REQUIRING external_id, name, slug, type — same block fields as blocks.create), dry_run (boolean — return the created/updated/unchanged/deleted plan without applying; run this first), prune (boolean — soft-delete remote blocks missing from the payload; destructive, only set when explicitly asked), commit_message (string, recorded on block versions). Blocks are matched by external_id, falling back to slug for adopting existing blocks. Updates automatically create restorable block versions. Unlike blocks.create/update this is a declarative full-set operation — always send every block that should exist, not just changed ones.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks/sync',
    ],
    // Block Templates
    'blocks.listTemplates' => [
        'description' => 'List templates for a block definition.',
        'required' => ['spaceId', 'blockId'],
        'accepts' => ['spaceId', 'blockId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks/{blockId}/templates',
    ],
    'blocks.createTemplate' => [
        'description' => 'Create a template for a block definition.',
        'required' => ['spaceId', 'blockId', 'payload'],
        'accepts' => ['spaceId', 'blockId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks/{blockId}/templates',
    ],
    'blocks.getTemplate' => [
        'description' => 'Get a block template by ID.',
        'required' => ['spaceId', 'blockId', 'templateId'],
        'accepts' => ['spaceId', 'blockId', 'templateId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks/{blockId}/templates/{templateId}',
    ],
    'blocks.updateTemplate' => [
        'description' => 'Update a block template.',
        'required' => ['spaceId', 'blockId', 'templateId', 'payload'],
        'accepts' => ['spaceId', 'blockId', 'templateId', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks/{blockId}/templates/{templateId}',
    ],
    'blocks.deleteTemplate' => [
        'description' => 'Delete a block template.',
        'required' => ['spaceId', 'blockId', 'templateId'],
        'accepts' => ['spaceId', 'blockId', 'templateId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks/{blockId}/templates/{templateId}',
    ],
    // Block Versions
    'blocks.listVersions' => [
        'description' => 'List versions of a block definition.',
        'required' => ['spaceId', 'blockId'],
        'accepts' => ['spaceId', 'blockId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks/{blockId}/versions',
    ],
    'blocks.getVersion' => [
        'description' => 'Get a specific version of a block definition.',
        'required' => ['spaceId', 'blockId', 'versionId'],
        'accepts' => ['spaceId', 'blockId', 'versionId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks/{blockId}/versions/{versionId}',
    ],
    'blocks.updateVersion' => [
        'description' => 'Update a block version.',
        'required' => ['spaceId', 'blockId', 'versionId', 'payload'],
        'accepts' => ['spaceId', 'blockId', 'versionId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks/{blockId}/versions/{versionId}',
    ],
    'blocks.deleteVersion' => [
        'description' => 'Delete a block version.',
        'required' => ['spaceId', 'blockId', 'versionId'],
        'accepts' => ['spaceId', 'blockId', 'versionId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks/{blockId}/versions/{versionId}',
    ],
    'blocks.restoreVersion' => [
        'description' => 'Restore a block version as the current definition.',
        'required' => ['spaceId', 'blockId', 'versionId'],
        'accepts' => ['spaceId', 'blockId', 'versionId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/blocks/{blockId}/versions/{versionId}/restore',
    ],

    // ─── Contents ───────────────────────────────────────────────────────────────
    'contents.list' => [
        'description' => 'List content entries in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents',
    ],
    'contents.create' => [
        'description' => 'Create a content entry.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents',
    ],
    'contents.get' => [
        'description' => 'Get a content entry by ID.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'contentId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}',
    ],
    'contents.update' => [
        'description' => 'Update a content entry.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'contentId', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}',
    ],
    'contents.delete' => [
        'description' => 'Delete a content entry.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'contentId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}',
    ],
    'contents.bulkCreate' => [
        'description' => 'Bulk-create multiple content entries at once.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/bulk-create',
    ],
    'contents.treeOperations' => [
        'description' => 'Perform batch tree operations on content (move, reorder, nest).',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/tree-operations',
    ],
    'contents.serialPreview' => [
        'description' => 'Preview the values a new entry would receive for its serial fields. '
            .'A peek, not a reservation — the number is only taken when the entry is created.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/serial-preview',
    ],
    'contents.move' => [
        'description' => 'Move a content entry to a different parent or position.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'contentId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/move',
    ],
    'contents.publish' => [
        'description' => 'Publish a content entry.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'contentId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/publish',
    ],
    'contents.unpublish' => [
        'description' => 'Unpublish a content entry.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'contentId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/unpublish',
    ],
    'contents.schedule' => [
        'description' => 'Schedule a content entry for publish/unpublish at a specific time.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'contentId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/schedule',
    ],
    // Content Versions
    'contents.listVersions' => [
        'description' => 'List versions of a content entry.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'contentId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/versions',
    ],
    'contents.getVersion' => [
        'description' => 'Get a specific version of a content entry.',
        'required' => ['spaceId', 'id', 'versionId'],
        'accepts' => ['spaceId', 'id', 'contentId', 'versionId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/versions/{versionId}',
    ],
    'contents.updateVersion' => [
        'description' => 'Update a content version (e.g. set a label/message).',
        'required' => ['spaceId', 'id', 'versionId', 'payload'],
        'accepts' => ['spaceId', 'id', 'contentId', 'versionId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/versions/{versionId}',
    ],
    'contents.publishVersion' => [
        'description' => 'Publish a specific content version.',
        'required' => ['spaceId', 'id', 'versionId'],
        'accepts' => ['spaceId', 'id', 'contentId', 'versionId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/versions/{versionId}/publish',
    ],
    'contents.setVersionAsCurrent' => [
        'description' => 'Set a content version as the current draft.',
        'required' => ['spaceId', 'id', 'versionId'],
        'accepts' => ['spaceId', 'id', 'contentId', 'versionId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/versions/{versionId}/current',
    ],

    // ─── Comments ───────────────────────────────────────────────────────────────
    'comments.list' => [
        'description' => 'List comments on a content entry.',
        'required' => ['spaceId', 'contentId'],
        'accepts' => ['spaceId', 'contentId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/comments',
    ],
    'comments.create' => [
        'description' => 'Add a comment to a content entry.',
        'required' => ['spaceId', 'contentId', 'payload'],
        'accepts' => ['spaceId', 'contentId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/comments',
    ],
    'comments.get' => [
        'description' => 'Get a comment by ID.',
        'required' => ['spaceId', 'contentId', 'commentId'],
        'accepts' => ['spaceId', 'contentId', 'commentId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/comments/{commentId}',
    ],
    'comments.update' => [
        'description' => 'Update a comment.',
        'required' => ['spaceId', 'contentId', 'commentId', 'payload'],
        'accepts' => ['spaceId', 'contentId', 'commentId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/comments/{commentId}',
    ],
    'comments.delete' => [
        'description' => 'Delete a comment.',
        'required' => ['spaceId', 'contentId', 'commentId'],
        'accepts' => ['spaceId', 'contentId', 'commentId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/comments/{commentId}',
    ],
    'comments.resolve' => [
        'description' => 'Mark a comment as resolved.',
        'required' => ['spaceId', 'contentId', 'commentId'],
        'accepts' => ['spaceId', 'contentId', 'commentId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/comments/{commentId}/resolve',
    ],
    'comments.unresolve' => [
        'description' => 'Mark a comment as unresolved.',
        'required' => ['spaceId', 'contentId', 'commentId'],
        'accepts' => ['spaceId', 'contentId', 'commentId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/comments/{commentId}/resolve',
    ],
    'comments.listReactions' => [
        'description' => 'List reactions on a comment.',
        'required' => ['spaceId', 'contentId', 'commentId'],
        'accepts' => ['spaceId', 'contentId', 'commentId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/comments/{commentId}/reactions',
    ],
    'comments.addReaction' => [
        'description' => 'Add a reaction to a comment.',
        'required' => ['spaceId', 'contentId', 'commentId', 'payload'],
        'accepts' => ['spaceId', 'contentId', 'commentId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/comments/{commentId}/reactions',
    ],
    'comments.removeReaction' => [
        'description' => 'Remove your reaction from a comment.',
        'required' => ['spaceId', 'contentId', 'commentId'],
        'accepts' => ['spaceId', 'contentId', 'commentId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/{contentId}/comments/{commentId}/reactions',
    ],

    // ─── Redirects ──────────────────────────────────────────────────────────────
    'redirects.exportData' => [
        'description' => 'Export redirects as CSV/JSON.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/redirects/export',
    ],
    'redirects.importData' => [
        'description' => 'Import redirects from CSV/JSON.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/redirects/import',
    ],

    // ─── Data Sources ────────────────────────────────────────────────────────────
    'dataSources.exportEntries' => [
        'description' => 'Export data source entries.',
        'required' => ['spaceId', 'dataSourceId'],
        'accepts' => ['spaceId', 'dataSourceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/data-sources/{dataSourceId}/entries/export',
    ],
    'dataSources.importEntries' => [
        'description' => 'Import entries into a data source.',
        'required' => ['spaceId', 'dataSourceId', 'payload'],
        'accepts' => ['spaceId', 'dataSourceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/data-sources/{dataSourceId}/entries/import',
    ],
    'dataSources.translateMissingDimensions' => [
        'description' => 'Trigger AI translation for missing locale dimensions in a data source.',
        'required' => ['spaceId', 'dataSourceId'],
        'accepts' => ['spaceId', 'dataSourceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/data-sources/{dataSourceId}/entries/translate-missing-dimensions/stream',
    ],

    // ─── Automations ─────────────────────────────────────────────────────────────
    // Actions
    'automations.listActions' => [
        'description' => 'List automation actions in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automation-actions',
    ],
    'automations.createAction' => [
        'description' => 'Create an automation action.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automation-actions',
    ],
    'automations.getAction' => [
        'description' => 'Get an automation action by ID.',
        'required' => ['spaceId', 'actionId'],
        'accepts' => ['spaceId', 'actionId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automation-actions/{actionId}',
    ],
    'automations.updateAction' => [
        'description' => 'Update an automation action.',
        'required' => ['spaceId', 'actionId', 'payload'],
        'accepts' => ['spaceId', 'actionId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automation-actions/{actionId}',
    ],
    'automations.deleteAction' => [
        'description' => 'Delete an automation action.',
        'required' => ['spaceId', 'actionId'],
        'accepts' => ['spaceId', 'actionId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automation-actions/{actionId}',
    ],
    // Automation CRUD
    'automations.getTriggerCatalog' => [
        'description' => 'Get the catalog of available automation triggers.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automations/trigger-catalog',
    ],
    'automations.list' => [
        'description' => 'List automations in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automations',
    ],
    'automations.create' => [
        'description' => 'Create an automation.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automations',
    ],
    'automations.get' => [
        'description' => 'Get an automation by ID.',
        'required' => ['spaceId', 'automationId'],
        'accepts' => ['spaceId', 'automationId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automations/{automationId}',
    ],
    'automations.update' => [
        'description' => 'Update an automation.',
        'required' => ['spaceId', 'automationId', 'payload'],
        'accepts' => ['spaceId', 'automationId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automations/{automationId}',
    ],
    'automations.delete' => [
        'description' => 'Delete an automation.',
        'required' => ['spaceId', 'automationId'],
        'accepts' => ['spaceId', 'automationId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automations/{automationId}',
    ],
    'automations.trigger' => [
        'description' => 'Manually trigger an automation.',
        'required' => ['spaceId', 'automationId'],
        'accepts' => ['spaceId', 'automationId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automations/{automationId}/trigger',
    ],
    // Stats
    'automations.statsExecutions' => [
        'description' => 'Get execution count stats for an automation.',
        'required' => ['spaceId', 'automationId'],
        'accepts' => ['spaceId', 'automationId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automations/{automationId}/stats/executions',
    ],
    'automations.statsTrends' => [
        'description' => 'Get trend stats for an automation.',
        'required' => ['spaceId', 'automationId'],
        'accepts' => ['spaceId', 'automationId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automations/{automationId}/stats/trends',
    ],
    'automations.statsStatistics' => [
        'description' => 'Get detailed statistics for an automation.',
        'required' => ['spaceId', 'automationId'],
        'accepts' => ['spaceId', 'automationId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automations/{automationId}/stats/statistics',
    ],
    'automations.statsSummary' => [
        'description' => 'Get a summary of automation statistics.',
        'required' => ['spaceId', 'automationId'],
        'accepts' => ['spaceId', 'automationId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automations/{automationId}/stats/summary',
    ],
    // Executions
    'automations.listExecutions' => [
        'description' => 'List automation execution history.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automation-executions',
    ],
    'automations.replayExecution' => [
        'description' => 'Replay a failed or completed automation execution.',
        'required' => ['spaceId', 'executionId'],
        'accepts' => ['spaceId', 'executionId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/automation-executions/{executionId}/replay',
    ],

    // ─── Releases ────────────────────────────────────────────────────────────────
    'releases.list' => [
        'description' => 'List releases in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/releases',
    ],
    'releases.create' => [
        'description' => 'Create a release.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/releases',
    ],
    'releases.get' => [
        'description' => 'Get a release by ID.',
        'required' => ['spaceId', 'releaseId'],
        'accepts' => ['spaceId', 'releaseId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/releases/{releaseId}',
    ],
    'releases.update' => [
        'description' => 'Update a release.',
        'required' => ['spaceId', 'releaseId', 'payload'],
        'accepts' => ['spaceId', 'releaseId', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/releases/{releaseId}',
    ],
    'releases.delete' => [
        'description' => 'Delete a release.',
        'required' => ['spaceId', 'releaseId'],
        'accepts' => ['spaceId', 'releaseId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/releases/{releaseId}',
    ],
    'releases.commit' => [
        'description' => 'Commit a release (finalize its content snapshot).',
        'required' => ['spaceId', 'releaseId'],
        'accepts' => ['spaceId', 'releaseId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/releases/{releaseId}/commit',
    ],
    'releases.cancel' => [
        'description' => 'Cancel a release.',
        'required' => ['spaceId', 'releaseId'],
        'accepts' => ['spaceId', 'releaseId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/releases/{releaseId}/cancel',
    ],
    'releases.publish' => [
        'description' => 'Publish all content versions in a release.',
        'required' => ['spaceId', 'releaseId'],
        'accepts' => ['spaceId', 'releaseId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/releases/{releaseId}/publish',
    ],
    'releases.assignVersion' => [
        'description' => 'Assign a content version to a release.',
        'required' => ['spaceId', 'releaseId', 'payload'],
        'accepts' => ['spaceId', 'releaseId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/releases/{releaseId}/versions/assign',
    ],
    'releases.removeVersion' => [
        'description' => 'Remove a content version from a release.',
        'required' => ['spaceId', 'releaseId', 'payload'],
        'accepts' => ['spaceId', 'releaseId', 'payload'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/releases/{releaseId}/versions/remove',
    ],

    // ─── AI ─────────────────────────────────────────────────────────────────────
    'ai.availableModels' => [
        'description' => 'List available AI models.',
        'accepts' => ['params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/ai/available-models',
    ],
    'ai.metaTags' => [
        'description' => 'Generate AI meta tags.',
        'required' => ['payload'],
        'accepts' => ['payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/ai/meta-tags/stream',
    ],
    'ai.translate' => [
        'description' => 'Translate content with AI.',
        'required' => ['payload'],
        'accepts' => ['payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/ai/translate/stream',
    ],

    // ─── Provider ────────────────────────────────────────────────────────────────
    'provider.getStats' => [
        'description' => 'Get provider-level statistics.',
        'method' => 'GET',
        'uri' => '/mgmt/v1/provider/stats',
    ],
    'provider.listNotes' => [
        'description' => 'List provider notes.',
        'accepts' => ['params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/provider/notes',
    ],
    'provider.createNote' => [
        'description' => 'Create a provider note.',
        'required' => ['payload'],
        'accepts' => ['payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/provider/notes',
    ],
    'provider.getNote' => [
        'description' => 'Get a provider note by ID.',
        'required' => ['noteId'],
        'accepts' => ['noteId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/provider/notes/{noteId}',
    ],
    'provider.updateNote' => [
        'description' => 'Update a provider note.',
        'required' => ['noteId', 'payload'],
        'accepts' => ['noteId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/provider/notes/{noteId}',
    ],
    'provider.deleteNote' => [
        'description' => 'Delete a provider note.',
        'required' => ['noteId'],
        'accepts' => ['noteId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/provider/notes/{noteId}',
    ],

    // ─── CRUD resources via loop ──────────────────────────────────────────────────

    'assets.list' => [
        'description' => 'List assets in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/assets',
    ],
    'assets.create' => [
        'description' => 'Create a asset.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/assets',
    ],
    'assets.get' => [
        'description' => 'Get a asset by ID.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/assets/{assetId}',
    ],
    'assets.update' => [
        'description' => 'Update a asset.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/assets/{assetId}',
    ],
    'assets.delete' => [
        'description' => 'Delete a asset.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/assets/{assetId}',
    ],

    'assetFolders.list' => [
        'description' => 'List asset folders in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-folders',
    ],
    'assetFolders.create' => [
        'description' => 'Create a asset folder.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-folders',
    ],
    'assetFolders.get' => [
        'description' => 'Get a asset folder by ID.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-folders/{folderId}',
    ],
    'assetFolders.update' => [
        'description' => 'Update a asset folder.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-folders/{folderId}',
    ],
    'assetFolders.delete' => [
        'description' => 'Delete a asset folder.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-folders/{folderId}',
    ],

    'assetTags.list' => [
        'description' => 'List asset tags in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-tags',
    ],
    'assetTags.create' => [
        'description' => 'Create a asset tag.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-tags',
    ],
    'assetTags.get' => [
        'description' => 'Get a asset tag by ID.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-tags/{tagId}',
    ],
    'assetTags.update' => [
        'description' => 'Update a asset tag.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-tags/{tagId}',
    ],
    'assetTags.delete' => [
        'description' => 'Delete a asset tag.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-tags/{tagId}',
    ],

    'blockFolders.list' => [
        'description' => 'List block folders in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/block-folders',
    ],
    'blockFolders.create' => [
        'description' => 'Create a block folder.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/block-folders',
    ],
    'blockFolders.get' => [
        'description' => 'Get a block folder by ID.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/block-folders/{folderId}',
    ],
    'blockFolders.update' => [
        'description' => 'Update a block folder.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/block-folders/{folderId}',
    ],
    'blockFolders.delete' => [
        'description' => 'Delete a block folder.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/block-folders/{folderId}',
    ],

    'blockTags.list' => [
        'description' => 'List block tags in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/block-tags',
    ],
    'blockTags.create' => [
        'description' => 'Create a block tag.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/block-tags',
    ],
    'blockTags.get' => [
        'description' => 'Get a block tag by ID.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/block-tags/{tagId}',
    ],
    'blockTags.update' => [
        'description' => 'Update a block tag.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/block-tags/{tagId}',
    ],
    'blockTags.delete' => [
        'description' => 'Delete a block tag.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/block-tags/{tagId}',
    ],

    'icons.list' => [
        'description' => 'List icons in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/icons',
    ],
    'icons.create' => [
        'description' => 'Create a icon.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/icons',
    ],
    'icons.get' => [
        'description' => 'Get a icon by ID.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/icons/{iconId}',
    ],
    'icons.update' => [
        'description' => 'Update a icon.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/icons/{iconId}',
    ],
    'icons.delete' => [
        'description' => 'Delete a icon.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/icons/{iconId}',
    ],

    'redirects.list' => [
        'description' => 'List redirects in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/redirects',
    ],
    'redirects.create' => [
        'description' => 'Create a redirect.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/redirects',
    ],
    'redirects.get' => [
        'description' => 'Get a redirect by ID.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/redirects/{redirectId}',
    ],
    'redirects.update' => [
        'description' => 'Update a redirect.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/redirects/{redirectId}',
    ],
    'redirects.delete' => [
        'description' => 'Delete a redirect.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/redirects/{redirectId}',
    ],

    'dataSources.list' => [
        'description' => 'List data sources in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/data-sources',
    ],
    'dataSources.create' => [
        'description' => 'Create a data source.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/data-sources',
    ],
    'dataSources.get' => [
        'description' => 'Get a data source by ID.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/data-sources/{dataSourceId}',
    ],
    'dataSources.update' => [
        'description' => 'Update a data source.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/data-sources/{dataSourceId}',
    ],
    'dataSources.delete' => [
        'description' => 'Delete a data source.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/data-sources/{dataSourceId}',
    ],

    'fieldPlugins.list' => [
        'description' => 'List field plugins of a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/field-plugins',
    ],
    'fieldPlugins.create' => [
        'description' => 'Create a field plugin (sandboxed iframe custom field). The handle is immutable after creation.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/field-plugins',
    ],
    'fieldPlugins.get' => [
        'description' => 'Get a field plugin.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'fieldPluginId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/field-plugins/{fieldPluginId}',
    ],
    'fieldPlugins.update' => [
        'description' => 'Update a field plugin. The handle cannot be changed.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'fieldPluginId', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/field-plugins/{fieldPluginId}',
    ],
    'fieldPlugins.delete' => [
        'description' => 'Delete a field plugin.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'fieldPluginId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/field-plugins/{fieldPluginId}',
    ],

    'icons.tags' => [
        'description' => 'List distinct tags used across icons in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/icons/tags',
    ],
    'assetTags.assign' => [
        'description' => 'Assign an asset tag to one or more assets. Payload fields: asset_ids (string[]).',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'tagId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-tags/{tagId}/assign',
    ],
    'redirects.reset' => [
        'description' => 'Reset redirect hit counters.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'redirectId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/redirects/{redirectId}/reset',
    ],
    'tokens.list' => [
        'description' => 'List access tokens for a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/tokens',
    ],
    'tokens.create' => [
        'description' => 'Create a space token.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/tokens',
    ],
    'tokens.delete' => [
        'description' => 'Delete a space token.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'tokenId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/tokens/{tokenId}',
    ],
    'dataSources.entries.list' => [
        'description' => 'List entries in a data source.',
        'required' => ['spaceId', 'dataSourceId'],
        'accepts' => ['spaceId', 'dataSourceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/data-sources/{dataSourceId}/entries',
    ],
    'dataSources.entries.create' => [
        'description' => 'Create a data source entry.',
        'required' => ['spaceId', 'dataSourceId', 'payload'],
        'accepts' => ['spaceId', 'dataSourceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/data-sources/{dataSourceId}/entries',
    ],
    'dataSources.entries.get' => [
        'description' => 'Get a data source entry.',
        'required' => ['spaceId', 'dataSourceId', 'entryId'],
        'accepts' => ['spaceId', 'dataSourceId', 'entryId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/data-sources/{dataSourceId}/entries/{entryId}',
    ],
    'dataSources.entries.update' => [
        'description' => 'Update a data source entry.',
        'required' => ['spaceId', 'dataSourceId', 'entryId', 'payload'],
        'accepts' => ['spaceId', 'dataSourceId', 'entryId', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/data-sources/{dataSourceId}/entries/{entryId}',
    ],
    'dataSources.entries.delete' => [
        'description' => 'Delete a data source entry.',
        'required' => ['spaceId', 'dataSourceId', 'entryId'],
        'accepts' => ['spaceId', 'dataSourceId', 'entryId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/data-sources/{dataSourceId}/entries/{entryId}',
    ],

    // ─── Asset Collections ────────────────────────────────────────────────────────

    'assetCollections.list' => [
        'description' => 'List asset collections in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-collections',
    ],
    'assetCollections.create' => [
        'description' => 'Create an asset collection. Payload fields: name (required), description, icon, color, type (manual|smart), rules (required for smart), settings, cover_asset_id, external_id.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-collections',
    ],
    'assetCollections.get' => [
        'description' => 'Get an asset collection by ID.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'collectionId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-collections/{collectionId}',
    ],
    'assetCollections.update' => [
        'description' => 'Update an asset collection.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'collectionId', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-collections/{collectionId}',
    ],
    'assetCollections.delete' => [
        'description' => 'Delete an asset collection. The assets themselves are kept.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'collectionId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-collections/{collectionId}',
    ],
    'assetCollections.listAssets' => [
        'description' => 'List the assets in a collection.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'collectionId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-collections/{collectionId}/assets',
    ],
    'assetCollections.addAssets' => [
        'description' => 'Add assets to a manual collection. Payload fields: asset_ids (string[]). Smart collections reject this.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'collectionId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-collections/{collectionId}/assets',
    ],
    'assetCollections.removeAssets' => [
        'description' => 'Remove assets from a manual collection. Payload fields: asset_ids (string[]). Smart collections reject this.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'collectionId', 'payload'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-collections/{collectionId}/assets',
    ],
    'assetCollections.reorderAssets' => [
        'description' => 'Reorder a manual collection. Payload fields: asset_ids (string[]) — the full ordered list.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'collectionId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-collections/{collectionId}/assets/order',
    ],

    // ─── Asset Shares & Packages ──────────────────────────────────────────────────

    'assetShares.list' => [
        'description' => 'List asset shares in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-shares',
    ],
    'assetShares.create' => [
        'description' => 'Create a public asset share. Payload fields: name (required), source_type (required: collection|selection|folder), collection_id / folder_id / asset_ids per source_type, description, password, expires_at, download_limit, allow_individual_downloads, settings.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-shares',
    ],
    'assetShares.get' => [
        'description' => 'Get an asset share by ID.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'shareId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-shares/{shareId}',
    ],
    'assetShares.update' => [
        'description' => 'Update an asset share. Omit password to keep it, pass null to remove it. Changing the source rebuilds the package.',
        'required' => ['spaceId', 'id', 'payload'],
        'accepts' => ['spaceId', 'id', 'shareId', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-shares/{shareId}',
    ],
    'assetShares.delete' => [
        'description' => 'Delete an asset share.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'shareId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-shares/{shareId}',
    ],
    'assetShares.revoke' => [
        'description' => 'Revoke an asset share, blocking further public access.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'shareId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-shares/{shareId}/revoke',
    ],
    'assetPackages.list' => [
        'description' => 'List asset packages (zip archives) in a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-packages',
    ],
    'assetPackages.create' => [
        'description' => 'Queue an asset package build. Payload fields: source_type (required: collection|selection|folder), collection_id / folder_id / asset_ids per source_type, name. Poll assetPackages.get until state is completed.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-packages',
    ],
    'assetPackages.get' => [
        'description' => 'Get an asset package, including its build state and progress.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'packageId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-packages/{packageId}',
    ],
    'assetPackages.delete' => [
        'description' => 'Delete an asset package and its archive.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'packageId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-packages/{packageId}',
    ],
    'assetPackages.download' => [
        'description' => 'Get a presigned download URL for a built package. Errors with 409 while it is still building.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'packageId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/asset-packages/{packageId}/download',
    ],

    // ─── Public Shares ────────────────────────────────────────────────────────────

    'shares.get' => [
        'description' => 'Read a public share by space id and token. Password-protected shares return only the name unless accessToken is supplied.',
        'required' => ['spaceId', 'token'],
        'accepts' => ['spaceId', 'token', 'accessToken'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/shares/{spaceId}/{token}',
        'authArg' => 'accessToken',
    ],
    'shares.unlock' => [
        'description' => 'Exchange a share password for a short-lived access token. Payload fields: password (string).',
        'required' => ['spaceId', 'token', 'payload'],
        'accepts' => ['spaceId', 'token', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/shares/{spaceId}/{token}/unlock',
    ],
    'shares.listAssets' => [
        'description' => 'List the assets in a public share.',
        'required' => ['spaceId', 'token'],
        'accepts' => ['spaceId', 'token', 'accessToken', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/shares/{spaceId}/{token}/assets',
        'authArg' => 'accessToken',
    ],
    'shares.download' => [
        'description' => 'Get a download URL for a public share archive. Returns build state while the archive is still being prepared.',
        'required' => ['spaceId', 'token'],
        'accepts' => ['spaceId', 'token', 'accessToken'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/shares/{spaceId}/{token}/download',
        'authArg' => 'accessToken',
    ],
    'shares.downloadAsset' => [
        'description' => 'Get a download URL for one asset in a public share.',
        'required' => ['spaceId', 'token', 'assetId'],
        'accepts' => ['spaceId', 'token', 'assetId', 'accessToken'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/shares/{spaceId}/{token}/assets/{assetId}/download',
        'authArg' => 'accessToken',
    ],

    // ─── Asset versions ───────────────────────────────────────────────────────────

    'assets.listVersions' => [
        'description' => 'List an asset’s file versions, most recent first.',
        'required' => ['spaceId', 'assetId'],
        'accepts' => ['spaceId', 'assetId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/assets/{assetId}/versions',
    ],
    'assets.restoreVersion' => [
        'description' => 'Restore an asset to an earlier version. The current file is snapshotted first, so this is reversible.',
        'required' => ['spaceId', 'assetId', 'versionId'],
        'accepts' => ['spaceId', 'assetId', 'versionId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/assets/{assetId}/versions/{versionId}/restore',
    ],
    'assets.linkedContents' => [
        'description' => 'List the contents that reference an asset.',
        'required' => ['spaceId', 'assetId'],
        'accepts' => ['spaceId', 'assetId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/assets/{assetId}/linked-contents',
    ],
    'assets.export' => [
        'description' => 'Export asset metadata.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/assets/export',
    ],

    // ─── Notifications ────────────────────────────────────────────────────────────

    'notifications.list' => [
        'description' => 'List the authenticated user’s notifications. Params: unread_only (bool), type (string), page, per_page.',
        'accepts' => ['params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/users/me/notifications',
    ],
    'notifications.unreadCount' => [
        'description' => 'Count the authenticated user’s unread notifications.',
        'method' => 'GET',
        'uri' => '/mgmt/v1/users/me/notifications/unread-count',
    ],
    'notifications.markRead' => [
        'description' => 'Mark one notification as read.',
        'required' => ['id'],
        'accepts' => ['id', 'notificationId'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/users/me/notifications/{notificationId}/read',
    ],
    'notifications.markUnread' => [
        'description' => 'Mark one notification as unread.',
        'required' => ['id'],
        'accepts' => ['id', 'notificationId'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/users/me/notifications/{notificationId}/unread',
    ],
    'notifications.markAllRead' => [
        'description' => 'Mark every notification as read.',
        'method' => 'POST',
        'uri' => '/mgmt/v1/users/me/notifications/read',
    ],
    'notifications.delete' => [
        'description' => 'Delete one notification.',
        'required' => ['id'],
        'accepts' => ['id', 'notificationId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/users/me/notifications/{notificationId}',
    ],
    'notifications.deleteRead' => [
        'description' => 'Delete every notification that has already been read.',
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/users/me/notifications/read',
    ],
    'notifications.deleteAll' => [
        'description' => 'Delete every notification, read or not.',
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/users/me/notifications',
    ],

    // ─── Usage & billing ──────────────────────────────────────────────────────────

    'spaces.usage' => [
        'description' => 'Read live usage for the current billing period.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/usage',
    ],
    'spaces.usageHistory' => [
        'description' => 'List usage rolled up per billing period, newest first.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/usage/history',
    ],
    'spaces.usageTimeseries' => [
        'description' => 'Read day-bucketed usage for one billing period. Params: metric (traffic|requests, defaults to traffic).',
        'required' => ['spaceId', 'periodId'],
        'accepts' => ['spaceId', 'periodId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/usage/history/{periodId}/timeseries',
    ],
    'spaces.listInvoices' => [
        'description' => 'List billing invoices for a space.',
        'required' => ['spaceId'],
        'accepts' => ['spaceId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/invoices',
    ],
    'spaces.updateOnboarding' => [
        'description' => 'Dismiss or restore the space onboarding guide. Payload fields: dismissed (boolean, required).',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/spaces/{spaceId}/onboarding',
    ],
    'spaces.getMigration' => [
        'description' => 'Get a space migration by ID.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'migrationId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/spaces/{spaceId}/migrations/{migrationId}',
    ],
    'spaces.deleteMigration' => [
        'description' => 'Delete a space migration.',
        'required' => ['spaceId', 'id'],
        'accepts' => ['spaceId', 'id', 'migrationId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/spaces/{spaceId}/migrations/{migrationId}',
    ],

    // ─── Contents export ──────────────────────────────────────────────────────────

    'contents.export' => [
        'description' => 'Export content. Payload fields: as (required: csv|excel|json|xliff|yaml) plus any content list filter.',
        'required' => ['spaceId', 'payload'],
        'accepts' => ['spaceId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/spaces/{spaceId}/contents/export',
    ],

    // ─── System ───────────────────────────────────────────────────────────────────

    'system.plans' => [
        'description' => 'List the available subscription plans.',
        'method' => 'GET',
        'uri' => '/mgmt/v1/plans',
    ],
    'system.authorization' => [
        'description' => 'Read the caller’s effective permissions. Params: team_id or space_id to resolve one context.',
        'accepts' => ['params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/authorization',
    ],
    'system.spaceBlueprints' => [
        'description' => 'List the space blueprints the caller can create a space from.',
        'accepts' => ['params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/space-blueprints',
    ],
    'system.getInvite' => [
        'description' => 'Read a public invite by ID, without authenticating.',
        'required' => ['id'],
        'accepts' => ['id', 'inviteId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/invites/{inviteId}',
    ],

    // ─── AI ───────────────────────────────────────────────────────────────────────

    'ai.models' => [
        'description' => 'List the AI models configured for the caller.',
        'method' => 'GET',
        'uri' => '/mgmt/v1/ai/models',
    ],
    'ai.contentInteraction' => [
        'description' => 'Run an AI interaction against a content entry. Returns the raw server-sent event stream as text.',
        'required' => ['payload'],
        'accepts' => ['payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/ai/content-interaction/stream',
    ],
    'ai.contentTreeInteraction' => [
        'description' => 'Run an AI interaction against a content tree. Returns the raw server-sent event stream as text.',
        'required' => ['payload'],
        'accepts' => ['payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/ai/content-tree-interaction/stream',
    ],

    // ─── Teams ────────────────────────────────────────────────────────────────────

    'teams.listPeople' => [
        'description' => 'List people of a team: members and pending invites in one directory. Params: q, sort, page, per_page.',
        'required' => ['teamId'],
        'accepts' => ['teamId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/teams/{teamId}/people',
    ],
    'teams.listMembers' => [
        'description' => 'List team members. Params: role, name, email, q, isActive, sort, page, per_page.',
        'required' => ['teamId'],
        'accepts' => ['teamId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/teams/{teamId}/members',
    ],
    'teams.updateMember' => [
        'description' => 'Update a team member’s role. Payload fields: role (string|null).',
        'required' => ['teamId', 'userId', 'payload'],
        'accepts' => ['teamId', 'userId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/teams/{teamId}/members/{userId}',
    ],
    'teams.removeMember' => [
        'description' => 'Remove a member from a team.',
        'required' => ['teamId', 'userId'],
        'accepts' => ['teamId', 'userId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/teams/{teamId}/members/{userId}',
    ],
    'teams.updateUser' => [
        'description' => 'Update a team user.',
        'required' => ['teamId', 'userId', 'payload'],
        'accepts' => ['teamId', 'userId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/teams/{teamId}/users/{userId}',
    ],
    'teams.listInvites' => [
        'description' => 'List pending team invites.',
        'required' => ['teamId'],
        'accepts' => ['teamId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/teams/{teamId}/invites',
    ],
    'teams.createInvite' => [
        'description' => 'Invite someone to a team. Payload fields: email (required), role, message.',
        'required' => ['teamId', 'payload'],
        'accepts' => ['teamId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/teams/{teamId}/invites',
    ],
    'teams.deleteInvite' => [
        'description' => 'Delete a team invite.',
        'required' => ['teamId', 'inviteId'],
        'accepts' => ['teamId', 'inviteId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/teams/{teamId}/invites/{inviteId}',
    ],
    'teams.resendInvite' => [
        'description' => 'Resend a team invite email.',
        'required' => ['teamId', 'inviteId'],
        'accepts' => ['teamId', 'inviteId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/teams/{teamId}/invites/{inviteId}/resend',
    ],
    'teams.getSamlProvider' => [
        'description' => 'Read a team’s SAML provider configuration.',
        'required' => ['teamId'],
        'accepts' => ['teamId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/teams/{teamId}/saml-provider',
    ],
    'teams.upsertSamlProvider' => [
        'description' => 'Create or replace a team’s SAML provider configuration.',
        'required' => ['teamId', 'payload'],
        'accepts' => ['teamId', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/teams/{teamId}/saml-provider',
    ],
    'teams.deleteSamlProvider' => [
        'description' => 'Delete a team’s SAML provider configuration.',
        'required' => ['teamId'],
        'accepts' => ['teamId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/teams/{teamId}/saml-provider',
    ],
    'teams.listBlueprints' => [
        'description' => 'List a team’s space blueprints.',
        'required' => ['teamId'],
        'accepts' => ['teamId', 'params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/teams/{teamId}/blueprints',
    ],
    'teams.createBlueprint' => [
        'description' => 'Create a space blueprint. Payload fields: name (required), icon, color, description, settings, data.',
        'required' => ['teamId', 'payload'],
        'accepts' => ['teamId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/teams/{teamId}/blueprints',
    ],
    'teams.getBlueprint' => [
        'description' => 'Get a space blueprint by ID.',
        'required' => ['teamId', 'id'],
        'accepts' => ['teamId', 'id', 'blueprintId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/teams/{teamId}/blueprints/{blueprintId}',
    ],
    'teams.updateBlueprint' => [
        'description' => 'Update a space blueprint.',
        'required' => ['teamId', 'id', 'payload'],
        'accepts' => ['teamId', 'id', 'blueprintId', 'payload'],
        'method' => 'PUT',
        'uri' => '/mgmt/v1/teams/{teamId}/blueprints/{blueprintId}',
    ],
    'teams.deleteBlueprint' => [
        'description' => 'Delete a space blueprint.',
        'required' => ['teamId', 'id'],
        'accepts' => ['teamId', 'id', 'blueprintId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/teams/{teamId}/blueprints/{blueprintId}',
    ],
    'teams.listSpaceRoles' => [
        'description' => 'List the space roles defined for a team.',
        'required' => ['teamId'],
        'accepts' => ['teamId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/teams/{teamId}/roles/space',
    ],
    'teams.createSpaceRole' => [
        'description' => 'Create a space role. Payload fields: name (required), key, description, abilities.',
        'required' => ['teamId', 'payload'],
        'accepts' => ['teamId', 'payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/teams/{teamId}/roles/space',
    ],
    'teams.updateSpaceRole' => [
        'description' => 'Update a space role.',
        'required' => ['teamId', 'id', 'payload'],
        'accepts' => ['teamId', 'id', 'roleId', 'payload'],
        'method' => 'PATCH',
        'uri' => '/mgmt/v1/teams/{teamId}/roles/space/{roleId}',
    ],
    'teams.deleteSpaceRole' => [
        'description' => 'Delete a space role.',
        'required' => ['teamId', 'id'],
        'accepts' => ['teamId', 'id', 'roleId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/teams/{teamId}/roles/space/{roleId}',
    ],

    // ─── Users ────────────────────────────────────────────────────────────────────

    'users.updateSettings' => [
        'description' => 'Update the authenticated user’s settings.',
        'required' => ['payload'],
        'accepts' => ['payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/users/me/settings',
    ],
    'users.updatePassword' => [
        'description' => 'Change the authenticated user’s password. Payload fields: current_password, password, password_confirmation.',
        'required' => ['payload'],
        'accepts' => ['payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/users/me/password',
    ],
    'users.listSocialLinks' => [
        'description' => 'List the authenticated user’s linked social accounts.',
        'method' => 'GET',
        'uri' => '/mgmt/v1/users/me/social-links',
    ],
    'users.deleteSocialLink' => [
        'description' => 'Unlink a social account by provider name.',
        'required' => ['provider'],
        'accepts' => ['provider'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/users/me/social-links/{provider}',
    ],
    'users.listTokens' => [
        'description' => 'List the authenticated user’s personal access tokens.',
        'accepts' => ['params'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/users/me/tokens',
    ],
    'users.createToken' => [
        'description' => 'Create a personal access token. Payload fields: name (required), abilities.',
        'required' => ['payload'],
        'accepts' => ['payload'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/users/me/tokens',
    ],
    'users.deleteToken' => [
        'description' => 'Delete a personal access token.',
        'required' => ['id'],
        'accepts' => ['id', 'tokenId'],
        'method' => 'DELETE',
        'uri' => '/mgmt/v1/users/me/tokens/{tokenId}',
    ],
    'users.listInvites' => [
        'description' => 'List invites addressed to the authenticated user.',
        'method' => 'GET',
        'uri' => '/mgmt/v1/users/me/invites',
    ],
    'users.getInvite' => [
        'description' => 'Get one invite addressed to the authenticated user.',
        'required' => ['id'],
        'accepts' => ['id', 'inviteId'],
        'method' => 'GET',
        'uri' => '/mgmt/v1/users/me/invites/{inviteId}',
    ],
    'users.acceptInvite' => [
        'description' => 'Accept an invite addressed to the authenticated user.',
        'required' => ['id'],
        'accepts' => ['id', 'inviteId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/users/me/invites/{inviteId}/accept',
    ],
    'users.declineInvite' => [
        'description' => 'Decline an invite addressed to the authenticated user.',
        'required' => ['id'],
        'accepts' => ['id', 'inviteId'],
        'method' => 'POST',
        'uri' => '/mgmt/v1/users/me/invites/{inviteId}/decline',
    ],
];
