<?php

namespace App\Services\Automation;

use App\Models\Management\Space;
use App\Models\Space\Asset;
use App\Models\Space\AssetFolder;
use App\Models\Space\AssetTag;
use App\Models\Space\Block;
use App\Models\Space\BlockFolder;
use App\Models\Space\BlockTag;
use App\Models\Space\BlockTemplate;
use App\Models\Space\BlockVersion;
use App\Models\Space\Comment;
use App\Models\Space\CommentReaction;
use App\Models\Space\Content;
use App\Models\Space\ContentVersion;
use App\Models\Space\DataEntry;
use App\Models\Space\DataSource;
use App\Models\Space\Redirect;
use App\Models\Space\Release;
use App\Services\Automation\Enums\TriggerType;
use App\Services\Database\DatabaseConnectionService;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;

class TriggerCatalog
{
    /**
     * @var array<string, class-string<Model>>
     */
    private const TABLE_MODELS = [
        'asset_folders' => AssetFolder::class,
        'asset_tags' => AssetTag::class,
        'assets' => Asset::class,
        'block_folders' => BlockFolder::class,
        'block_tags' => BlockTag::class,
        'block_templates' => BlockTemplate::class,
        // 'block_versions' => BlockVersion::class,
        'blocks' => Block::class,
        'comment_reactions' => CommentReaction::class,
        'comments' => Comment::class,
        'content_versions' => ContentVersion::class,
        'contents' => Content::class,
        'data_entries' => DataEntry::class,
        'data_sources' => DataSource::class,
        'redirects' => Redirect::class,
        'releases' => Release::class,
    ];

    /**
     * @var array<string, string>
     */
    private const TABLE_DESCRIPTIONS = [
        'comment_reactions' => 'Emoji reactions attached to editorial comments.',
        'comments' => 'Editorial comments and review threads on content.',
        'data_entries' => 'Records stored inside reusable data sources.',
        'data_sources' => 'Data source definitions and availability settings.',
        'redirects' => 'URL redirects generated by editors and publishing flows.',
        'content_versions' => 'Draft, scheduled, and published content versions.',
        'contents' => 'Primary content entries managed in the CMS.',
        'releases' => 'Release records used to schedule publishing batches.',
        'block_versions' => 'Version history for block schemas and settings.',
        'block_templates' => 'Reusable templates attached to blocks.',
        'blocks' => 'Content type and schema definitions.',
        'block_tags' => 'Tags used to organize blocks.',
        'block_folders' => 'Folders used to group blocks.',
        'assets' => 'Files managed in the asset library.',
        'asset_folders' => 'Folders used to organize assets.',
        'asset_tags' => 'Tags used to classify assets.',
    ];

    /**
     * @var array<string, array<int, string>>
     */
    private array $columnsCache = [];

    public function __construct(
        private readonly DatabaseConnectionService $databaseConnectionService,
    ) {
    }

    /**
     * @return array<int, string>
     */
    public function tables(): array
    {
        return array_keys(self::TABLE_MODELS);
    }

    public function supportsTable(?string $table): bool
    {
        return is_string($table) && array_key_exists($table, self::TABLE_MODELS);
    }

    public function supportsModel(Model $model): bool
    {
        return $this->supportsTable($model->getTable());
    }

    public function resolveTableFromConfig(?array $config): ?string
    {
        $table = trim((string) data_get($config, 'table', data_get($config, 'resource', '')));

        return $table === '' ? null : $table;
    }

    public function labelForTable(string $table): string
    {
        return Str::headline(Str::singular($table));
    }

    public function descriptionForTable(string $table): string
    {
        return self::TABLE_DESCRIPTIONS[$table] ?? sprintf(
            'Events emitted from the %s table.',
            $this->labelForTable($table),
        );
    }

    /**
     * @return array<int, string>
     */
    public function columnsForTable(string $table, Space $space): array
    {
        if (!$this->supportsTable($table)) {
            return [];
        }

        $defaultConnection = $space->defaultConnection->first();

        $connection = $defaultConnection
            ? $this->databaseConnectionService->getConnection($defaultConnection)
            : app('db')->connection();
        $cacheKey = sprintf('%s:%s', $connection->getName(), $table);

        if (!array_key_exists($cacheKey, $this->columnsCache)) {
            $schema = $connection->getSchemaBuilder();
            $columns = $schema->hasTable($table)
                ? $schema->getColumnListing($table)
                : [];

            sort($columns);
            $this->columnsCache[$cacheKey] = array_values($columns);
        }

        return $this->columnsCache[$cacheKey];
    }

    /**
     * @return array<int, array<string, mixed>>
     */
    public function forSpace(Space $space): array
    {
        return $this->definitions()
            ->map(fn(array $definition): array => [
                ...$definition,
                'columns' => $this->columnsForTable($definition['table'], $space),
            ])
            ->values()
            ->all();
    }

    /**
     * @return Collection<int, array<string, mixed>>
     */
    public function definitions(): Collection
    {
        return collect($this->tables())->map(fn(string $table): array => [
            'table' => $table,
            'label' => $this->labelForTable($table),
            'description' => $this->descriptionForTable($table),
        ]);
    }

    /**
     * @return array<string, array{label: string, description: string, table: string}>
     */
    public function contentLifecycleTriggers(): array
    {
        return [
            TriggerType::CONTENT_PUBLISHED->value => [
                'trigger_type' => TriggerType::CONTENT_PUBLISHED->value,
                'table' => 'contents',
                'label' => 'Content Published',
                'description' => 'Fires when a content entry transitions from unpublished to published.',
            ],
            TriggerType::CONTENT_UNPUBLISHED->value => [
                'trigger_type' => TriggerType::CONTENT_UNPUBLISHED->value,
                'table' => 'contents',
                'label' => 'Content Unpublished',
                'description' => 'Fires when a published content entry is taken offline.',
            ],
        ];
    }
}
